module GI.Gtk.Interfaces.CellAccessibleParent where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype CellAccessibleParent = CellAccessibleParent (ForeignPtr CellAccessibleParent)
class ForeignPtrNewtype a => CellAccessibleParentK a
instance (ForeignPtrNewtype o, IsDescendantOf CellAccessibleParent o) => CellAccessibleParentK o
data CellAccessibleParentActivateMethodInfo
data CellAccessibleParentEditMethodInfo
data CellAccessibleParentExpandCollapseMethodInfo
data CellAccessibleParentGetCellAreaMethodInfo
data CellAccessibleParentGetCellExtentsMethodInfo
data CellAccessibleParentGetChildIndexMethodInfo
data CellAccessibleParentGetRendererStateMethodInfo
data CellAccessibleParentGrabFocusMethodInfo
data CellAccessibleParentUpdateRelationsetMethodInfo
