module GI.Gtk.Interfaces.FileChooser where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype FileChooser = FileChooser (ForeignPtr FileChooser)
data FileChooserActionPropertyInfo
data FileChooserCreateFoldersPropertyInfo
data FileChooserDoOverwriteConfirmationPropertyInfo
data FileChooserExtraWidgetPropertyInfo
data FileChooserFilterPropertyInfo
data FileChooserLocalOnlyPropertyInfo
data FileChooserPreviewWidgetPropertyInfo
data FileChooserPreviewWidgetActivePropertyInfo
data FileChooserSelectMultiplePropertyInfo
data FileChooserShowHiddenPropertyInfo
data FileChooserUsePreviewLabelPropertyInfo
data FileChooserConfirmOverwriteSignalInfo
data FileChooserCurrentFolderChangedSignalInfo
data FileChooserFileActivatedSignalInfo
data FileChooserSelectionChangedSignalInfo
data FileChooserUpdatePreviewSignalInfo
instance GObject FileChooser where
class GObject o => FileChooserK o
instance (GObject o, IsDescendantOf FileChooser o) => FileChooserK o
data FileChooserAddFilterMethodInfo
data FileChooserAddShortcutFolderMethodInfo
data FileChooserAddShortcutFolderUriMethodInfo
data FileChooserGetActionMethodInfo
data FileChooserGetCreateFoldersMethodInfo
data FileChooserGetCurrentFolderMethodInfo
data FileChooserGetCurrentFolderFileMethodInfo
data FileChooserGetCurrentFolderUriMethodInfo
data FileChooserGetCurrentNameMethodInfo
data FileChooserGetDoOverwriteConfirmationMethodInfo
data FileChooserGetExtraWidgetMethodInfo
data FileChooserGetFileMethodInfo
data FileChooserGetFilenameMethodInfo
data FileChooserGetFilenamesMethodInfo
data FileChooserGetFilesMethodInfo
data FileChooserGetFilterMethodInfo
data FileChooserGetLocalOnlyMethodInfo
data FileChooserGetPreviewFileMethodInfo
data FileChooserGetPreviewFilenameMethodInfo
data FileChooserGetPreviewUriMethodInfo
data FileChooserGetPreviewWidgetMethodInfo
data FileChooserGetPreviewWidgetActiveMethodInfo
data FileChooserGetSelectMultipleMethodInfo
data FileChooserGetShowHiddenMethodInfo
data FileChooserGetUriMethodInfo
data FileChooserGetUrisMethodInfo
data FileChooserGetUsePreviewLabelMethodInfo
data FileChooserListFiltersMethodInfo
data FileChooserListShortcutFolderUrisMethodInfo
data FileChooserListShortcutFoldersMethodInfo
data FileChooserRemoveFilterMethodInfo
data FileChooserRemoveShortcutFolderMethodInfo
data FileChooserRemoveShortcutFolderUriMethodInfo
data FileChooserSelectAllMethodInfo
data FileChooserSelectFileMethodInfo
data FileChooserSelectFilenameMethodInfo
data FileChooserSelectUriMethodInfo
data FileChooserSetActionMethodInfo
data FileChooserSetCreateFoldersMethodInfo
data FileChooserSetCurrentFolderMethodInfo
data FileChooserSetCurrentFolderFileMethodInfo
data FileChooserSetCurrentFolderUriMethodInfo
data FileChooserSetCurrentNameMethodInfo
data FileChooserSetDoOverwriteConfirmationMethodInfo
data FileChooserSetExtraWidgetMethodInfo
data FileChooserSetFileMethodInfo
data FileChooserSetFilenameMethodInfo
data FileChooserSetFilterMethodInfo
data FileChooserSetLocalOnlyMethodInfo
data FileChooserSetPreviewWidgetMethodInfo
data FileChooserSetPreviewWidgetActiveMethodInfo
data FileChooserSetSelectMultipleMethodInfo
data FileChooserSetShowHiddenMethodInfo
data FileChooserSetUriMethodInfo
data FileChooserSetUsePreviewLabelMethodInfo
data FileChooserUnselectAllMethodInfo
data FileChooserUnselectFileMethodInfo
data FileChooserUnselectFilenameMethodInfo
data FileChooserUnselectUriMethodInfo
