module GI.GstVideo.Structs.VideoOverlayRectangle where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype VideoOverlayRectangle = VideoOverlayRectangle (ForeignPtr VideoOverlayRectangle)
instance BoxedObject VideoOverlayRectangle where
data VideoOverlayRectangleCopyMethodInfo
data VideoOverlayRectangleGetFlagsMethodInfo
data VideoOverlayRectangleGetGlobalAlphaMethodInfo
data VideoOverlayRectangleGetPixelsArgbMethodInfo
data VideoOverlayRectangleGetPixelsAyuvMethodInfo
data VideoOverlayRectangleGetPixelsRawMethodInfo
data VideoOverlayRectangleGetPixelsUnscaledArgbMethodInfo
data VideoOverlayRectangleGetPixelsUnscaledAyuvMethodInfo
data VideoOverlayRectangleGetPixelsUnscaledRawMethodInfo
data VideoOverlayRectangleGetRenderRectangleMethodInfo
data VideoOverlayRectangleGetSeqnumMethodInfo
data VideoOverlayRectangleSetGlobalAlphaMethodInfo
data VideoOverlayRectangleSetRenderRectangleMethodInfo
