module GI.GstVideo.Structs.VideoOverlayComposition where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype VideoOverlayComposition = VideoOverlayComposition (ForeignPtr VideoOverlayComposition)
instance BoxedObject VideoOverlayComposition where
data VideoOverlayCompositionAddRectangleMethodInfo
data VideoOverlayCompositionBlendMethodInfo
data VideoOverlayCompositionCopyMethodInfo
data VideoOverlayCompositionGetRectangleMethodInfo
data VideoOverlayCompositionGetSeqnumMethodInfo
data VideoOverlayCompositionMakeWritableMethodInfo
data VideoOverlayCompositionNRectanglesMethodInfo
