module GI.WebKit.Objects.DOMHTMLMediaElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLMediaElement = DOMHTMLMediaElement (ForeignPtr DOMHTMLMediaElement)
instance GObject DOMHTMLMediaElement where
class GObject o => DOMHTMLMediaElementK o
instance (GObject o, IsDescendantOf DOMHTMLMediaElement o) => DOMHTMLMediaElementK o
data DOMHTMLMediaElementAudioTracksPropertyInfo
data DOMHTMLMediaElementAutoplayPropertyInfo
data DOMHTMLMediaElementBufferedPropertyInfo
data DOMHTMLMediaElementControllerPropertyInfo
data DOMHTMLMediaElementControlsPropertyInfo
data DOMHTMLMediaElementCurrentSrcPropertyInfo
data DOMHTMLMediaElementCurrentTimePropertyInfo
data DOMHTMLMediaElementDefaultMutedPropertyInfo
data DOMHTMLMediaElementDefaultPlaybackRatePropertyInfo
data DOMHTMLMediaElementDurationPropertyInfo
data DOMHTMLMediaElementEndedPropertyInfo
data DOMHTMLMediaElementErrorPropertyInfo
data DOMHTMLMediaElementLoopPropertyInfo
data DOMHTMLMediaElementMediaGroupPropertyInfo
data DOMHTMLMediaElementMutedPropertyInfo
data DOMHTMLMediaElementNetworkStatePropertyInfo
data DOMHTMLMediaElementPausedPropertyInfo
data DOMHTMLMediaElementPlaybackRatePropertyInfo
data DOMHTMLMediaElementPlayedPropertyInfo
data DOMHTMLMediaElementPreloadPropertyInfo
data DOMHTMLMediaElementReadyStatePropertyInfo
data DOMHTMLMediaElementSeekablePropertyInfo
data DOMHTMLMediaElementSeekingPropertyInfo
data DOMHTMLMediaElementSrcPropertyInfo
data DOMHTMLMediaElementTextTracksPropertyInfo
data DOMHTMLMediaElementVideoTracksPropertyInfo
data DOMHTMLMediaElementVolumePropertyInfo
data DOMHTMLMediaElementWebkitAudioDecodedByteCountPropertyInfo
data DOMHTMLMediaElementWebkitClosedCaptionsVisiblePropertyInfo
data DOMHTMLMediaElementWebkitCurrentPlaybackTargetIsWirelessPropertyInfo
data DOMHTMLMediaElementWebkitHasClosedCaptionsPropertyInfo
data DOMHTMLMediaElementWebkitPreservesPitchPropertyInfo
data DOMHTMLMediaElementWebkitVideoDecodedByteCountPropertyInfo
data DOMHTMLMediaElementAddTextTrackMethodInfo
data DOMHTMLMediaElementCanPlayTypeMethodInfo
data DOMHTMLMediaElementFastSeekMethodInfo
data DOMHTMLMediaElementGetAudioTracksMethodInfo
data DOMHTMLMediaElementGetAutoplayMethodInfo
data DOMHTMLMediaElementGetBufferedMethodInfo
data DOMHTMLMediaElementGetControllerMethodInfo
data DOMHTMLMediaElementGetControlsMethodInfo
data DOMHTMLMediaElementGetCurrentSrcMethodInfo
data DOMHTMLMediaElementGetCurrentTimeMethodInfo
data DOMHTMLMediaElementGetDefaultMutedMethodInfo
data DOMHTMLMediaElementGetDefaultPlaybackRateMethodInfo
data DOMHTMLMediaElementGetDurationMethodInfo
data DOMHTMLMediaElementGetEndedMethodInfo
data DOMHTMLMediaElementGetErrorMethodInfo
data DOMHTMLMediaElementGetInitialTimeMethodInfo
data DOMHTMLMediaElementGetLoopMethodInfo
data DOMHTMLMediaElementGetMediaGroupMethodInfo
data DOMHTMLMediaElementGetMutedMethodInfo
data DOMHTMLMediaElementGetNetworkStateMethodInfo
data DOMHTMLMediaElementGetPausedMethodInfo
data DOMHTMLMediaElementGetPlaybackRateMethodInfo
data DOMHTMLMediaElementGetPlayedMethodInfo
data DOMHTMLMediaElementGetPreloadMethodInfo
data DOMHTMLMediaElementGetReadyStateMethodInfo
data DOMHTMLMediaElementGetSeekableMethodInfo
data DOMHTMLMediaElementGetSeekingMethodInfo
data DOMHTMLMediaElementGetSrcMethodInfo
data DOMHTMLMediaElementGetStartTimeMethodInfo
data DOMHTMLMediaElementGetTextTracksMethodInfo
data DOMHTMLMediaElementGetVideoTracksMethodInfo
data DOMHTMLMediaElementGetVolumeMethodInfo
data DOMHTMLMediaElementGetWebkitAudioDecodedByteCountMethodInfo
data DOMHTMLMediaElementGetWebkitClosedCaptionsVisibleMethodInfo
data DOMHTMLMediaElementGetWebkitCurrentPlaybackTargetIsWirelessMethodInfo
data DOMHTMLMediaElementGetWebkitHasClosedCaptionsMethodInfo
data DOMHTMLMediaElementGetWebkitPreservesPitchMethodInfo
data DOMHTMLMediaElementGetWebkitVideoDecodedByteCountMethodInfo
data DOMHTMLMediaElementLoadMethodInfo
data DOMHTMLMediaElementPauseMethodInfo
data DOMHTMLMediaElementPlayMethodInfo
data DOMHTMLMediaElementSetAutoplayMethodInfo
data DOMHTMLMediaElementSetControlsMethodInfo
data DOMHTMLMediaElementSetCurrentTimeMethodInfo
data DOMHTMLMediaElementSetDefaultMutedMethodInfo
data DOMHTMLMediaElementSetDefaultPlaybackRateMethodInfo
data DOMHTMLMediaElementSetLoopMethodInfo
data DOMHTMLMediaElementSetMediaGroupMethodInfo
data DOMHTMLMediaElementSetMutedMethodInfo
data DOMHTMLMediaElementSetPlaybackRateMethodInfo
data DOMHTMLMediaElementSetPreloadMethodInfo
data DOMHTMLMediaElementSetSrcMethodInfo
data DOMHTMLMediaElementSetVolumeMethodInfo
data DOMHTMLMediaElementSetWebkitClosedCaptionsVisibleMethodInfo
data DOMHTMLMediaElementSetWebkitPreservesPitchMethodInfo
data DOMHTMLMediaElementWebkitShowPlaybackTargetPickerMethodInfo
