module GI.WebKit.Objects.DOMHTMLTableCellElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLTableCellElement = DOMHTMLTableCellElement (ForeignPtr DOMHTMLTableCellElement)
instance GObject DOMHTMLTableCellElement where
class GObject o => DOMHTMLTableCellElementK o
instance (GObject o, IsDescendantOf DOMHTMLTableCellElement o) => DOMHTMLTableCellElementK o
data DOMHTMLTableCellElementAbbrPropertyInfo
data DOMHTMLTableCellElementAlignPropertyInfo
data DOMHTMLTableCellElementAxisPropertyInfo
data DOMHTMLTableCellElementBgColorPropertyInfo
data DOMHTMLTableCellElementCellIndexPropertyInfo
data DOMHTMLTableCellElementChPropertyInfo
data DOMHTMLTableCellElementChOffPropertyInfo
data DOMHTMLTableCellElementColSpanPropertyInfo
data DOMHTMLTableCellElementHeadersPropertyInfo
data DOMHTMLTableCellElementHeightPropertyInfo
data DOMHTMLTableCellElementNoWrapPropertyInfo
data DOMHTMLTableCellElementRowSpanPropertyInfo
data DOMHTMLTableCellElementScopePropertyInfo
data DOMHTMLTableCellElementVAlignPropertyInfo
data DOMHTMLTableCellElementWidthPropertyInfo
data DOMHTMLTableCellElementGetAbbrMethodInfo
data DOMHTMLTableCellElementGetAlignMethodInfo
data DOMHTMLTableCellElementGetAxisMethodInfo
data DOMHTMLTableCellElementGetBgColorMethodInfo
data DOMHTMLTableCellElementGetCellIndexMethodInfo
data DOMHTMLTableCellElementGetChMethodInfo
data DOMHTMLTableCellElementGetChOffMethodInfo
data DOMHTMLTableCellElementGetColSpanMethodInfo
data DOMHTMLTableCellElementGetHeadersMethodInfo
data DOMHTMLTableCellElementGetHeightMethodInfo
data DOMHTMLTableCellElementGetNoWrapMethodInfo
data DOMHTMLTableCellElementGetRowSpanMethodInfo
data DOMHTMLTableCellElementGetScopeMethodInfo
data DOMHTMLTableCellElementGetVAlignMethodInfo
data DOMHTMLTableCellElementGetWidthMethodInfo
data DOMHTMLTableCellElementSetAbbrMethodInfo
data DOMHTMLTableCellElementSetAlignMethodInfo
data DOMHTMLTableCellElementSetAxisMethodInfo
data DOMHTMLTableCellElementSetBgColorMethodInfo
data DOMHTMLTableCellElementSetChMethodInfo
data DOMHTMLTableCellElementSetChOffMethodInfo
data DOMHTMLTableCellElementSetColSpanMethodInfo
data DOMHTMLTableCellElementSetHeadersMethodInfo
data DOMHTMLTableCellElementSetHeightMethodInfo
data DOMHTMLTableCellElementSetNoWrapMethodInfo
data DOMHTMLTableCellElementSetRowSpanMethodInfo
data DOMHTMLTableCellElementSetScopeMethodInfo
data DOMHTMLTableCellElementSetVAlignMethodInfo
data DOMHTMLTableCellElementSetWidthMethodInfo
