module GI.WebKit.Objects.DOMHTMLIFrameElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLIFrameElement = DOMHTMLIFrameElement (ForeignPtr DOMHTMLIFrameElement)
instance GObject DOMHTMLIFrameElement where
class GObject o => DOMHTMLIFrameElementK o
instance (GObject o, IsDescendantOf DOMHTMLIFrameElement o) => DOMHTMLIFrameElementK o
data DOMHTMLIFrameElementAlignPropertyInfo
data DOMHTMLIFrameElementContentDocumentPropertyInfo
data DOMHTMLIFrameElementContentWindowPropertyInfo
data DOMHTMLIFrameElementFrameBorderPropertyInfo
data DOMHTMLIFrameElementHeightPropertyInfo
data DOMHTMLIFrameElementLongDescPropertyInfo
data DOMHTMLIFrameElementMarginHeightPropertyInfo
data DOMHTMLIFrameElementMarginWidthPropertyInfo
data DOMHTMLIFrameElementNamePropertyInfo
data DOMHTMLIFrameElementSandboxPropertyInfo
data DOMHTMLIFrameElementScrollingPropertyInfo
data DOMHTMLIFrameElementSeamlessPropertyInfo
data DOMHTMLIFrameElementSrcPropertyInfo
data DOMHTMLIFrameElementSrcdocPropertyInfo
data DOMHTMLIFrameElementWidthPropertyInfo
data DOMHTMLIFrameElementGetAlignMethodInfo
data DOMHTMLIFrameElementGetContentDocumentMethodInfo
data DOMHTMLIFrameElementGetContentWindowMethodInfo
data DOMHTMLIFrameElementGetFrameBorderMethodInfo
data DOMHTMLIFrameElementGetHeightMethodInfo
data DOMHTMLIFrameElementGetLongDescMethodInfo
data DOMHTMLIFrameElementGetMarginHeightMethodInfo
data DOMHTMLIFrameElementGetMarginWidthMethodInfo
data DOMHTMLIFrameElementGetNameMethodInfo
data DOMHTMLIFrameElementGetSandboxMethodInfo
data DOMHTMLIFrameElementGetScrollingMethodInfo
data DOMHTMLIFrameElementGetSeamlessMethodInfo
data DOMHTMLIFrameElementGetSrcMethodInfo
data DOMHTMLIFrameElementGetSrcdocMethodInfo
data DOMHTMLIFrameElementGetWidthMethodInfo
data DOMHTMLIFrameElementSetAlignMethodInfo
data DOMHTMLIFrameElementSetFrameBorderMethodInfo
data DOMHTMLIFrameElementSetHeightMethodInfo
data DOMHTMLIFrameElementSetLongDescMethodInfo
data DOMHTMLIFrameElementSetMarginHeightMethodInfo
data DOMHTMLIFrameElementSetMarginWidthMethodInfo
data DOMHTMLIFrameElementSetNameMethodInfo
data DOMHTMLIFrameElementSetSandboxMethodInfo
data DOMHTMLIFrameElementSetScrollingMethodInfo
data DOMHTMLIFrameElementSetSeamlessMethodInfo
data DOMHTMLIFrameElementSetSrcMethodInfo
data DOMHTMLIFrameElementSetSrcdocMethodInfo
data DOMHTMLIFrameElementSetWidthMethodInfo
