module GI.WebKit.Objects.DOMHTMLObjectElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLObjectElement = DOMHTMLObjectElement (ForeignPtr DOMHTMLObjectElement)
instance GObject DOMHTMLObjectElement where
class GObject o => DOMHTMLObjectElementK o
instance (GObject o, IsDescendantOf DOMHTMLObjectElement o) => DOMHTMLObjectElementK o
data DOMHTMLObjectElementAlignPropertyInfo
data DOMHTMLObjectElementArchivePropertyInfo
data DOMHTMLObjectElementBorderPropertyInfo
data DOMHTMLObjectElementCodePropertyInfo
data DOMHTMLObjectElementCodeBasePropertyInfo
data DOMHTMLObjectElementCodeTypePropertyInfo
data DOMHTMLObjectElementContentDocumentPropertyInfo
data DOMHTMLObjectElementDataPropertyInfo
data DOMHTMLObjectElementDeclarePropertyInfo
data DOMHTMLObjectElementFormPropertyInfo
data DOMHTMLObjectElementHeightPropertyInfo
data DOMHTMLObjectElementHspacePropertyInfo
data DOMHTMLObjectElementNamePropertyInfo
data DOMHTMLObjectElementStandbyPropertyInfo
data DOMHTMLObjectElementTypePropertyInfo
data DOMHTMLObjectElementUseMapPropertyInfo
data DOMHTMLObjectElementValidationMessagePropertyInfo
data DOMHTMLObjectElementValidityPropertyInfo
data DOMHTMLObjectElementVspacePropertyInfo
data DOMHTMLObjectElementWidthPropertyInfo
data DOMHTMLObjectElementWillValidatePropertyInfo
data DOMHTMLObjectElementCheckValidityMethodInfo
data DOMHTMLObjectElementGetAlignMethodInfo
data DOMHTMLObjectElementGetArchiveMethodInfo
data DOMHTMLObjectElementGetBorderMethodInfo
data DOMHTMLObjectElementGetCodeMethodInfo
data DOMHTMLObjectElementGetCodeBaseMethodInfo
data DOMHTMLObjectElementGetCodeTypeMethodInfo
data DOMHTMLObjectElementGetContentDocumentMethodInfo
data DOMHTMLObjectElementGetDataMethodInfo
data DOMHTMLObjectElementGetDeclareMethodInfo
data DOMHTMLObjectElementGetFormMethodInfo
data DOMHTMLObjectElementGetHeightMethodInfo
data DOMHTMLObjectElementGetHspaceMethodInfo
data DOMHTMLObjectElementGetNameMethodInfo
data DOMHTMLObjectElementGetStandbyMethodInfo
data DOMHTMLObjectElementGetUseMapMethodInfo
data DOMHTMLObjectElementGetValidationMessageMethodInfo
data DOMHTMLObjectElementGetValidityMethodInfo
data DOMHTMLObjectElementGetVspaceMethodInfo
data DOMHTMLObjectElementGetWidthMethodInfo
data DOMHTMLObjectElementGetWillValidateMethodInfo
data DOMHTMLObjectElementSetAlignMethodInfo
data DOMHTMLObjectElementSetArchiveMethodInfo
data DOMHTMLObjectElementSetBorderMethodInfo
data DOMHTMLObjectElementSetCodeMethodInfo
data DOMHTMLObjectElementSetCodeBaseMethodInfo
data DOMHTMLObjectElementSetCodeTypeMethodInfo
data DOMHTMLObjectElementSetCustomValidityMethodInfo
data DOMHTMLObjectElementSetDataMethodInfo
data DOMHTMLObjectElementSetDeclareMethodInfo
data DOMHTMLObjectElementSetHeightMethodInfo
data DOMHTMLObjectElementSetHspaceMethodInfo
data DOMHTMLObjectElementSetNameMethodInfo
data DOMHTMLObjectElementSetStandbyMethodInfo
data DOMHTMLObjectElementSetUseMapMethodInfo
data DOMHTMLObjectElementSetVspaceMethodInfo
data DOMHTMLObjectElementSetWidthMethodInfo
