module GI.WebKit.Objects.DOMHTMLMarqueeElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLMarqueeElement = DOMHTMLMarqueeElement (ForeignPtr DOMHTMLMarqueeElement)
instance GObject DOMHTMLMarqueeElement where
class GObject o => DOMHTMLMarqueeElementK o
instance (GObject o, IsDescendantOf DOMHTMLMarqueeElement o) => DOMHTMLMarqueeElementK o
data DOMHTMLMarqueeElementBehaviorPropertyInfo
data DOMHTMLMarqueeElementBgColorPropertyInfo
data DOMHTMLMarqueeElementDirectionPropertyInfo
data DOMHTMLMarqueeElementHeightPropertyInfo
data DOMHTMLMarqueeElementHspacePropertyInfo
data DOMHTMLMarqueeElementLoopPropertyInfo
data DOMHTMLMarqueeElementScrollAmountPropertyInfo
data DOMHTMLMarqueeElementScrollDelayPropertyInfo
data DOMHTMLMarqueeElementTrueSpeedPropertyInfo
data DOMHTMLMarqueeElementVspacePropertyInfo
data DOMHTMLMarqueeElementWidthPropertyInfo
data DOMHTMLMarqueeElementGetBehaviorMethodInfo
data DOMHTMLMarqueeElementGetBgColorMethodInfo
data DOMHTMLMarqueeElementGetDirectionMethodInfo
data DOMHTMLMarqueeElementGetHeightMethodInfo
data DOMHTMLMarqueeElementGetHspaceMethodInfo
data DOMHTMLMarqueeElementGetLoopMethodInfo
data DOMHTMLMarqueeElementGetScrollAmountMethodInfo
data DOMHTMLMarqueeElementGetScrollDelayMethodInfo
data DOMHTMLMarqueeElementGetTrueSpeedMethodInfo
data DOMHTMLMarqueeElementGetVspaceMethodInfo
data DOMHTMLMarqueeElementGetWidthMethodInfo
data DOMHTMLMarqueeElementSetBehaviorMethodInfo
data DOMHTMLMarqueeElementSetBgColorMethodInfo
data DOMHTMLMarqueeElementSetDirectionMethodInfo
data DOMHTMLMarqueeElementSetHeightMethodInfo
data DOMHTMLMarqueeElementSetHspaceMethodInfo
data DOMHTMLMarqueeElementSetLoopMethodInfo
data DOMHTMLMarqueeElementSetScrollAmountMethodInfo
data DOMHTMLMarqueeElementSetScrollDelayMethodInfo
data DOMHTMLMarqueeElementSetTrueSpeedMethodInfo
data DOMHTMLMarqueeElementSetVspaceMethodInfo
data DOMHTMLMarqueeElementSetWidthMethodInfo
data DOMHTMLMarqueeElementStartMethodInfo
data DOMHTMLMarqueeElementStopMethodInfo
