module GI.WebKit.Objects.DOMHTMLTableElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLTableElement = DOMHTMLTableElement (ForeignPtr DOMHTMLTableElement)
instance GObject DOMHTMLTableElement where
class GObject o => DOMHTMLTableElementK o
instance (GObject o, IsDescendantOf DOMHTMLTableElement o) => DOMHTMLTableElementK o
data DOMHTMLTableElementAlignPropertyInfo
data DOMHTMLTableElementBgColorPropertyInfo
data DOMHTMLTableElementBorderPropertyInfo
data DOMHTMLTableElementCaptionPropertyInfo
data DOMHTMLTableElementCellPaddingPropertyInfo
data DOMHTMLTableElementCellSpacingPropertyInfo
data DOMHTMLTableElementFramePropertyInfo
data DOMHTMLTableElementRowsPropertyInfo
data DOMHTMLTableElementRulesPropertyInfo
data DOMHTMLTableElementSummaryPropertyInfo
data DOMHTMLTableElementTBodiesPropertyInfo
data DOMHTMLTableElementTFootPropertyInfo
data DOMHTMLTableElementTHeadPropertyInfo
data DOMHTMLTableElementWidthPropertyInfo
data DOMHTMLTableElementCreateCaptionMethodInfo
data DOMHTMLTableElementCreateTBodyMethodInfo
data DOMHTMLTableElementCreateTFootMethodInfo
data DOMHTMLTableElementCreateTHeadMethodInfo
data DOMHTMLTableElementDeleteCaptionMethodInfo
data DOMHTMLTableElementDeleteRowMethodInfo
data DOMHTMLTableElementDeleteTFootMethodInfo
data DOMHTMLTableElementDeleteTHeadMethodInfo
data DOMHTMLTableElementGetAlignMethodInfo
data DOMHTMLTableElementGetBgColorMethodInfo
data DOMHTMLTableElementGetBorderMethodInfo
data DOMHTMLTableElementGetCaptionMethodInfo
data DOMHTMLTableElementGetCellPaddingMethodInfo
data DOMHTMLTableElementGetCellSpacingMethodInfo
data DOMHTMLTableElementGetFrameMethodInfo
data DOMHTMLTableElementGetRowsMethodInfo
data DOMHTMLTableElementGetRulesMethodInfo
data DOMHTMLTableElementGetSummaryMethodInfo
data DOMHTMLTableElementGetTBodiesMethodInfo
data DOMHTMLTableElementGetTFootMethodInfo
data DOMHTMLTableElementGetTHeadMethodInfo
data DOMHTMLTableElementGetWidthMethodInfo
data DOMHTMLTableElementInsertRowMethodInfo
data DOMHTMLTableElementSetAlignMethodInfo
data DOMHTMLTableElementSetBgColorMethodInfo
data DOMHTMLTableElementSetBorderMethodInfo
data DOMHTMLTableElementSetCaptionMethodInfo
data DOMHTMLTableElementSetCellPaddingMethodInfo
data DOMHTMLTableElementSetCellSpacingMethodInfo
data DOMHTMLTableElementSetFrameMethodInfo
data DOMHTMLTableElementSetRulesMethodInfo
data DOMHTMLTableElementSetSummaryMethodInfo
data DOMHTMLTableElementSetTFootMethodInfo
data DOMHTMLTableElementSetTHeadMethodInfo
data DOMHTMLTableElementSetWidthMethodInfo
