module GI.WebKit.Objects.DOMHTMLFormElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLFormElement = DOMHTMLFormElement (ForeignPtr DOMHTMLFormElement)
instance GObject DOMHTMLFormElement where
class GObject o => DOMHTMLFormElementK o
instance (GObject o, IsDescendantOf DOMHTMLFormElement o) => DOMHTMLFormElementK o
data DOMHTMLFormElementAcceptCharsetPropertyInfo
data DOMHTMLFormElementActionPropertyInfo
data DOMHTMLFormElementAutocapitalizePropertyInfo
data DOMHTMLFormElementAutocompletePropertyInfo
data DOMHTMLFormElementAutocorrectPropertyInfo
data DOMHTMLFormElementElementsPropertyInfo
data DOMHTMLFormElementEncodingPropertyInfo
data DOMHTMLFormElementEnctypePropertyInfo
data DOMHTMLFormElementLengthPropertyInfo
data DOMHTMLFormElementMethodPropertyInfo
data DOMHTMLFormElementNamePropertyInfo
data DOMHTMLFormElementNoValidatePropertyInfo
data DOMHTMLFormElementTargetPropertyInfo
data DOMHTMLFormElementCheckValidityMethodInfo
data DOMHTMLFormElementDispatchFormChangeMethodInfo
data DOMHTMLFormElementDispatchFormInputMethodInfo
data DOMHTMLFormElementGetAcceptCharsetMethodInfo
data DOMHTMLFormElementGetActionMethodInfo
data DOMHTMLFormElementGetAutocapitalizeMethodInfo
data DOMHTMLFormElementGetAutocompleteMethodInfo
data DOMHTMLFormElementGetAutocorrectMethodInfo
data DOMHTMLFormElementGetElementsMethodInfo
data DOMHTMLFormElementGetEncodingMethodInfo
data DOMHTMLFormElementGetEnctypeMethodInfo
data DOMHTMLFormElementGetLengthMethodInfo
data DOMHTMLFormElementGetMethodMethodInfo
data DOMHTMLFormElementGetNameMethodInfo
data DOMHTMLFormElementGetNoValidateMethodInfo
data DOMHTMLFormElementGetTargetMethodInfo
data DOMHTMLFormElementResetMethodInfo
data DOMHTMLFormElementSetAcceptCharsetMethodInfo
data DOMHTMLFormElementSetActionMethodInfo
data DOMHTMLFormElementSetAutocapitalizeMethodInfo
data DOMHTMLFormElementSetAutocompleteMethodInfo
data DOMHTMLFormElementSetAutocorrectMethodInfo
data DOMHTMLFormElementSetEncodingMethodInfo
data DOMHTMLFormElementSetEnctypeMethodInfo
data DOMHTMLFormElementSetMethodMethodInfo
data DOMHTMLFormElementSetNameMethodInfo
data DOMHTMLFormElementSetNoValidateMethodInfo
data DOMHTMLFormElementSetTargetMethodInfo
data DOMHTMLFormElementSubmitMethodInfo
