module GI.WebKit.Objects.DOMHTMLButtonElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLButtonElement = DOMHTMLButtonElement (ForeignPtr DOMHTMLButtonElement)
instance GObject DOMHTMLButtonElement where
class GObject o => DOMHTMLButtonElementK o
instance (GObject o, IsDescendantOf DOMHTMLButtonElement o) => DOMHTMLButtonElementK o
data DOMHTMLButtonElementAutofocusPropertyInfo
data DOMHTMLButtonElementDisabledPropertyInfo
data DOMHTMLButtonElementFormPropertyInfo
data DOMHTMLButtonElementFormActionPropertyInfo
data DOMHTMLButtonElementFormEnctypePropertyInfo
data DOMHTMLButtonElementFormMethodPropertyInfo
data DOMHTMLButtonElementFormNoValidatePropertyInfo
data DOMHTMLButtonElementFormTargetPropertyInfo
data DOMHTMLButtonElementLabelsPropertyInfo
data DOMHTMLButtonElementNamePropertyInfo
data DOMHTMLButtonElementTypePropertyInfo
data DOMHTMLButtonElementValidationMessagePropertyInfo
data DOMHTMLButtonElementValidityPropertyInfo
data DOMHTMLButtonElementValuePropertyInfo
data DOMHTMLButtonElementWillValidatePropertyInfo
data DOMHTMLButtonElementCheckValidityMethodInfo
data DOMHTMLButtonElementGetAutofocusMethodInfo
data DOMHTMLButtonElementGetDisabledMethodInfo
data DOMHTMLButtonElementGetFormMethodInfo
data DOMHTMLButtonElementGetFormActionMethodInfo
data DOMHTMLButtonElementGetFormEnctypeMethodInfo
data DOMHTMLButtonElementGetFormMethodMethodInfo
data DOMHTMLButtonElementGetFormNoValidateMethodInfo
data DOMHTMLButtonElementGetFormTargetMethodInfo
data DOMHTMLButtonElementGetLabelsMethodInfo
data DOMHTMLButtonElementGetNameMethodInfo
data DOMHTMLButtonElementGetValidationMessageMethodInfo
data DOMHTMLButtonElementGetValidityMethodInfo
data DOMHTMLButtonElementGetValueMethodInfo
data DOMHTMLButtonElementGetWillValidateMethodInfo
data DOMHTMLButtonElementSetAutofocusMethodInfo
data DOMHTMLButtonElementSetCustomValidityMethodInfo
data DOMHTMLButtonElementSetDisabledMethodInfo
data DOMHTMLButtonElementSetFormActionMethodInfo
data DOMHTMLButtonElementSetFormEnctypeMethodInfo
data DOMHTMLButtonElementSetFormMethodMethodInfo
data DOMHTMLButtonElementSetFormNoValidateMethodInfo
data DOMHTMLButtonElementSetFormTargetMethodInfo
data DOMHTMLButtonElementSetNameMethodInfo
data DOMHTMLButtonElementSetValueMethodInfo
