module GI.WebKit.Objects.DOMHTMLImageElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLImageElement = DOMHTMLImageElement (ForeignPtr DOMHTMLImageElement)
instance GObject DOMHTMLImageElement where
class GObject o => DOMHTMLImageElementK o
instance (GObject o, IsDescendantOf DOMHTMLImageElement o) => DOMHTMLImageElementK o
data DOMHTMLImageElementAlignPropertyInfo
data DOMHTMLImageElementAltPropertyInfo
data DOMHTMLImageElementBorderPropertyInfo
data DOMHTMLImageElementCompletePropertyInfo
data DOMHTMLImageElementCrossOriginPropertyInfo
data DOMHTMLImageElementHeightPropertyInfo
data DOMHTMLImageElementHspacePropertyInfo
data DOMHTMLImageElementIsMapPropertyInfo
data DOMHTMLImageElementLongDescPropertyInfo
data DOMHTMLImageElementLowsrcPropertyInfo
data DOMHTMLImageElementNamePropertyInfo
data DOMHTMLImageElementNaturalHeightPropertyInfo
data DOMHTMLImageElementNaturalWidthPropertyInfo
data DOMHTMLImageElementSrcPropertyInfo
data DOMHTMLImageElementSrcsetPropertyInfo
data DOMHTMLImageElementUseMapPropertyInfo
data DOMHTMLImageElementVspacePropertyInfo
data DOMHTMLImageElementWidthPropertyInfo
data DOMHTMLImageElementXPropertyInfo
data DOMHTMLImageElementYPropertyInfo
data DOMHTMLImageElementGetAlignMethodInfo
data DOMHTMLImageElementGetAltMethodInfo
data DOMHTMLImageElementGetBorderMethodInfo
data DOMHTMLImageElementGetCompleteMethodInfo
data DOMHTMLImageElementGetCrossOriginMethodInfo
data DOMHTMLImageElementGetHeightMethodInfo
data DOMHTMLImageElementGetHspaceMethodInfo
data DOMHTMLImageElementGetIsMapMethodInfo
data DOMHTMLImageElementGetLongDescMethodInfo
data DOMHTMLImageElementGetLowsrcMethodInfo
data DOMHTMLImageElementGetNameMethodInfo
data DOMHTMLImageElementGetNaturalHeightMethodInfo
data DOMHTMLImageElementGetNaturalWidthMethodInfo
data DOMHTMLImageElementGetSrcMethodInfo
data DOMHTMLImageElementGetSrcsetMethodInfo
data DOMHTMLImageElementGetUseMapMethodInfo
data DOMHTMLImageElementGetVspaceMethodInfo
data DOMHTMLImageElementGetWidthMethodInfo
data DOMHTMLImageElementGetXMethodInfo
data DOMHTMLImageElementGetYMethodInfo
data DOMHTMLImageElementSetAlignMethodInfo
data DOMHTMLImageElementSetAltMethodInfo
data DOMHTMLImageElementSetBorderMethodInfo
data DOMHTMLImageElementSetCrossOriginMethodInfo
data DOMHTMLImageElementSetHeightMethodInfo
data DOMHTMLImageElementSetHspaceMethodInfo
data DOMHTMLImageElementSetIsMapMethodInfo
data DOMHTMLImageElementSetLongDescMethodInfo
data DOMHTMLImageElementSetLowsrcMethodInfo
data DOMHTMLImageElementSetNameMethodInfo
data DOMHTMLImageElementSetSrcMethodInfo
data DOMHTMLImageElementSetSrcsetMethodInfo
data DOMHTMLImageElementSetUseMapMethodInfo
data DOMHTMLImageElementSetVspaceMethodInfo
data DOMHTMLImageElementSetWidthMethodInfo
