module GI.WebKit.Objects.DOMHTMLSelectElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLSelectElement = DOMHTMLSelectElement (ForeignPtr DOMHTMLSelectElement)
instance GObject DOMHTMLSelectElement where
class GObject o => DOMHTMLSelectElementK o
instance (GObject o, IsDescendantOf DOMHTMLSelectElement o) => DOMHTMLSelectElementK o
data DOMHTMLSelectElementAutofocusPropertyInfo
data DOMHTMLSelectElementDisabledPropertyInfo
data DOMHTMLSelectElementFormPropertyInfo
data DOMHTMLSelectElementLabelsPropertyInfo
data DOMHTMLSelectElementLengthPropertyInfo
data DOMHTMLSelectElementMultiplePropertyInfo
data DOMHTMLSelectElementNamePropertyInfo
data DOMHTMLSelectElementOptionsPropertyInfo
data DOMHTMLSelectElementRequiredPropertyInfo
data DOMHTMLSelectElementSelectedIndexPropertyInfo
data DOMHTMLSelectElementSelectedOptionsPropertyInfo
data DOMHTMLSelectElementSizePropertyInfo
data DOMHTMLSelectElementTypePropertyInfo
data DOMHTMLSelectElementValidationMessagePropertyInfo
data DOMHTMLSelectElementValidityPropertyInfo
data DOMHTMLSelectElementValuePropertyInfo
data DOMHTMLSelectElementWillValidatePropertyInfo
data DOMHTMLSelectElementAddMethodInfo
data DOMHTMLSelectElementCheckValidityMethodInfo
data DOMHTMLSelectElementGetAutofocusMethodInfo
data DOMHTMLSelectElementGetDisabledMethodInfo
data DOMHTMLSelectElementGetFormMethodInfo
data DOMHTMLSelectElementGetLabelsMethodInfo
data DOMHTMLSelectElementGetLengthMethodInfo
data DOMHTMLSelectElementGetMultipleMethodInfo
data DOMHTMLSelectElementGetNameMethodInfo
data DOMHTMLSelectElementGetOptionsMethodInfo
data DOMHTMLSelectElementGetRequiredMethodInfo
data DOMHTMLSelectElementGetSelectedIndexMethodInfo
data DOMHTMLSelectElementGetSelectedOptionsMethodInfo
data DOMHTMLSelectElementGetSizeMethodInfo
data DOMHTMLSelectElementGetValidationMessageMethodInfo
data DOMHTMLSelectElementGetValidityMethodInfo
data DOMHTMLSelectElementGetValueMethodInfo
data DOMHTMLSelectElementGetWillValidateMethodInfo
data DOMHTMLSelectElementItemMethodInfo
data DOMHTMLSelectElementNamedItemMethodInfo
data DOMHTMLSelectElementRemoveMethodInfo
data DOMHTMLSelectElementSetAutofocusMethodInfo
data DOMHTMLSelectElementSetCustomValidityMethodInfo
data DOMHTMLSelectElementSetDisabledMethodInfo
data DOMHTMLSelectElementSetLengthMethodInfo
data DOMHTMLSelectElementSetMultipleMethodInfo
data DOMHTMLSelectElementSetNameMethodInfo
data DOMHTMLSelectElementSetRequiredMethodInfo
data DOMHTMLSelectElementSetSelectedIndexMethodInfo
data DOMHTMLSelectElementSetSizeMethodInfo
data DOMHTMLSelectElementSetValueMethodInfo
