module GI.WebKit.Objects.DOMHTMLElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLElement = DOMHTMLElement (ForeignPtr DOMHTMLElement)
instance GObject DOMHTMLElement where
class GObject o => DOMHTMLElementK o
instance (GObject o, IsDescendantOf DOMHTMLElement o) => DOMHTMLElementK o
data DOMHTMLElementAccessKeyPropertyInfo
data DOMHTMLElementChildrenPropertyInfo
data DOMHTMLElementContentEditablePropertyInfo
data DOMHTMLElementDirPropertyInfo
data DOMHTMLElementDraggablePropertyInfo
data DOMHTMLElementHiddenPropertyInfo
data DOMHTMLElementInnerHtmlPropertyInfo
data DOMHTMLElementInnerTextPropertyInfo
data DOMHTMLElementIsContentEditablePropertyInfo
data DOMHTMLElementLangPropertyInfo
data DOMHTMLElementOuterHtmlPropertyInfo
data DOMHTMLElementOuterTextPropertyInfo
data DOMHTMLElementSpellcheckPropertyInfo
data DOMHTMLElementTabIndexPropertyInfo
data DOMHTMLElementTitlePropertyInfo
data DOMHTMLElementTranslatePropertyInfo
data DOMHTMLElementWebkitdropzonePropertyInfo
data DOMHTMLElementClickMethodInfo
data DOMHTMLElementGetAccessKeyMethodInfo
data DOMHTMLElementGetChildrenMethodInfo
data DOMHTMLElementGetClassListMethodInfo
data DOMHTMLElementGetClassNameMethodInfo
data DOMHTMLElementGetContentEditableMethodInfo
data DOMHTMLElementGetDirMethodInfo
data DOMHTMLElementGetDraggableMethodInfo
data DOMHTMLElementGetHiddenMethodInfo
data DOMHTMLElementGetIdMethodInfo
data DOMHTMLElementGetInnerHtmlMethodInfo
data DOMHTMLElementGetInnerTextMethodInfo
data DOMHTMLElementGetIsContentEditableMethodInfo
data DOMHTMLElementGetItemIdMethodInfo
data DOMHTMLElementGetItemPropMethodInfo
data DOMHTMLElementGetItemRefMethodInfo
data DOMHTMLElementGetItemScopeMethodInfo
data DOMHTMLElementGetItemTypeMethodInfo
data DOMHTMLElementGetLangMethodInfo
data DOMHTMLElementGetOuterHtmlMethodInfo
data DOMHTMLElementGetOuterTextMethodInfo
data DOMHTMLElementGetSpellcheckMethodInfo
data DOMHTMLElementGetTabIndexMethodInfo
data DOMHTMLElementGetTitleMethodInfo
data DOMHTMLElementGetTranslateMethodInfo
data DOMHTMLElementGetWebkitdropzoneMethodInfo
data DOMHTMLElementInsertAdjacentElementMethodInfo
data DOMHTMLElementInsertAdjacentHtmlMethodInfo
data DOMHTMLElementInsertAdjacentTextMethodInfo
data DOMHTMLElementSetAccessKeyMethodInfo
data DOMHTMLElementSetClassNameMethodInfo
data DOMHTMLElementSetContentEditableMethodInfo
data DOMHTMLElementSetDirMethodInfo
data DOMHTMLElementSetDraggableMethodInfo
data DOMHTMLElementSetHiddenMethodInfo
data DOMHTMLElementSetIdMethodInfo
data DOMHTMLElementSetInnerHtmlMethodInfo
data DOMHTMLElementSetInnerTextMethodInfo
data DOMHTMLElementSetItemIdMethodInfo
data DOMHTMLElementSetItemScopeMethodInfo
data DOMHTMLElementSetLangMethodInfo
data DOMHTMLElementSetOuterHtmlMethodInfo
data DOMHTMLElementSetOuterTextMethodInfo
data DOMHTMLElementSetSpellcheckMethodInfo
data DOMHTMLElementSetTabIndexMethodInfo
data DOMHTMLElementSetTitleMethodInfo
data DOMHTMLElementSetTranslateMethodInfo
data DOMHTMLElementSetWebkitdropzoneMethodInfo
