module GI.WebKit.Objects.DOMHTMLVideoElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLVideoElement = DOMHTMLVideoElement (ForeignPtr DOMHTMLVideoElement)
instance GObject DOMHTMLVideoElement where
class GObject o => DOMHTMLVideoElementK o
instance (GObject o, IsDescendantOf DOMHTMLVideoElement o) => DOMHTMLVideoElementK o
data DOMHTMLVideoElementHeightPropertyInfo
data DOMHTMLVideoElementPosterPropertyInfo
data DOMHTMLVideoElementVideoHeightPropertyInfo
data DOMHTMLVideoElementVideoWidthPropertyInfo
data DOMHTMLVideoElementWebkitDecodedFrameCountPropertyInfo
data DOMHTMLVideoElementWebkitDisplayingFullscreenPropertyInfo
data DOMHTMLVideoElementWebkitDroppedFrameCountPropertyInfo
data DOMHTMLVideoElementWebkitSupportsFullscreenPropertyInfo
data DOMHTMLVideoElementWebkitWirelessVideoPlaybackDisabledPropertyInfo
data DOMHTMLVideoElementWidthPropertyInfo
data DOMHTMLVideoElementGetHeightMethodInfo
data DOMHTMLVideoElementGetPosterMethodInfo
data DOMHTMLVideoElementGetVideoHeightMethodInfo
data DOMHTMLVideoElementGetVideoWidthMethodInfo
data DOMHTMLVideoElementGetWebkitDecodedFrameCountMethodInfo
data DOMHTMLVideoElementGetWebkitDisplayingFullscreenMethodInfo
data DOMHTMLVideoElementGetWebkitDroppedFrameCountMethodInfo
data DOMHTMLVideoElementGetWebkitSupportsFullscreenMethodInfo
data DOMHTMLVideoElementGetWebkitWirelessVideoPlaybackDisabledMethodInfo
data DOMHTMLVideoElementGetWidthMethodInfo
data DOMHTMLVideoElementSetHeightMethodInfo
data DOMHTMLVideoElementSetPosterMethodInfo
data DOMHTMLVideoElementSetWebkitWirelessVideoPlaybackDisabledMethodInfo
data DOMHTMLVideoElementSetWidthMethodInfo
data DOMHTMLVideoElementWebkitEnterFullScreenMethodInfo
data DOMHTMLVideoElementWebkitEnterFullscreenMethodInfo
data DOMHTMLVideoElementWebkitExitFullScreenMethodInfo
data DOMHTMLVideoElementWebkitExitFullscreenMethodInfo
