module GI.WebKit.Objects.DOMHTMLKeygenElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLKeygenElement = DOMHTMLKeygenElement (ForeignPtr DOMHTMLKeygenElement)
instance GObject DOMHTMLKeygenElement where
class GObject o => DOMHTMLKeygenElementK o
instance (GObject o, IsDescendantOf DOMHTMLKeygenElement o) => DOMHTMLKeygenElementK o
data DOMHTMLKeygenElementAutofocusPropertyInfo
data DOMHTMLKeygenElementChallengePropertyInfo
data DOMHTMLKeygenElementDisabledPropertyInfo
data DOMHTMLKeygenElementFormPropertyInfo
data DOMHTMLKeygenElementKeytypePropertyInfo
data DOMHTMLKeygenElementLabelsPropertyInfo
data DOMHTMLKeygenElementNamePropertyInfo
data DOMHTMLKeygenElementTypePropertyInfo
data DOMHTMLKeygenElementValidationMessagePropertyInfo
data DOMHTMLKeygenElementValidityPropertyInfo
data DOMHTMLKeygenElementWillValidatePropertyInfo
data DOMHTMLKeygenElementCheckValidityMethodInfo
data DOMHTMLKeygenElementGetAutofocusMethodInfo
data DOMHTMLKeygenElementGetChallengeMethodInfo
data DOMHTMLKeygenElementGetDisabledMethodInfo
data DOMHTMLKeygenElementGetFormMethodInfo
data DOMHTMLKeygenElementGetKeytypeMethodInfo
data DOMHTMLKeygenElementGetLabelsMethodInfo
data DOMHTMLKeygenElementGetNameMethodInfo
data DOMHTMLKeygenElementGetValidationMessageMethodInfo
data DOMHTMLKeygenElementGetValidityMethodInfo
data DOMHTMLKeygenElementGetWillValidateMethodInfo
data DOMHTMLKeygenElementSetAutofocusMethodInfo
data DOMHTMLKeygenElementSetChallengeMethodInfo
data DOMHTMLKeygenElementSetCustomValidityMethodInfo
data DOMHTMLKeygenElementSetDisabledMethodInfo
data DOMHTMLKeygenElementSetKeytypeMethodInfo
data DOMHTMLKeygenElementSetNameMethodInfo
