module GI.WebKit.Objects.DOMHTMLAppletElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMHTMLAppletElement = DOMHTMLAppletElement (ForeignPtr DOMHTMLAppletElement)
instance GObject DOMHTMLAppletElement where
class GObject o => DOMHTMLAppletElementK o
instance (GObject o, IsDescendantOf DOMHTMLAppletElement o) => DOMHTMLAppletElementK o
data DOMHTMLAppletElementAlignPropertyInfo
data DOMHTMLAppletElementAltPropertyInfo
data DOMHTMLAppletElementArchivePropertyInfo
data DOMHTMLAppletElementCodePropertyInfo
data DOMHTMLAppletElementCodeBasePropertyInfo
data DOMHTMLAppletElementHeightPropertyInfo
data DOMHTMLAppletElementHspacePropertyInfo
data DOMHTMLAppletElementNamePropertyInfo
data DOMHTMLAppletElementObjectPropertyInfo
data DOMHTMLAppletElementVspacePropertyInfo
data DOMHTMLAppletElementWidthPropertyInfo
data DOMHTMLAppletElementGetAlignMethodInfo
data DOMHTMLAppletElementGetAltMethodInfo
data DOMHTMLAppletElementGetArchiveMethodInfo
data DOMHTMLAppletElementGetCodeMethodInfo
data DOMHTMLAppletElementGetCodeBaseMethodInfo
data DOMHTMLAppletElementGetHeightMethodInfo
data DOMHTMLAppletElementGetHspaceMethodInfo
data DOMHTMLAppletElementGetNameMethodInfo
data DOMHTMLAppletElementGetObjectMethodInfo
data DOMHTMLAppletElementGetVspaceMethodInfo
data DOMHTMLAppletElementGetWidthMethodInfo
data DOMHTMLAppletElementSetAlignMethodInfo
data DOMHTMLAppletElementSetAltMethodInfo
data DOMHTMLAppletElementSetArchiveMethodInfo
data DOMHTMLAppletElementSetCodeMethodInfo
data DOMHTMLAppletElementSetCodeBaseMethodInfo
data DOMHTMLAppletElementSetHeightMethodInfo
data DOMHTMLAppletElementSetHspaceMethodInfo
data DOMHTMLAppletElementSetNameMethodInfo
data DOMHTMLAppletElementSetObjectMethodInfo
data DOMHTMLAppletElementSetVspaceMethodInfo
data DOMHTMLAppletElementSetWidthMethodInfo
