module GI.WebKit.Objects.DOMMediaController where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMMediaController = DOMMediaController (ForeignPtr DOMMediaController)
instance GObject DOMMediaController where
class GObject o => DOMMediaControllerK o
instance (GObject o, IsDescendantOf DOMMediaController o) => DOMMediaControllerK o
data DOMMediaControllerBufferedPropertyInfo
data DOMMediaControllerCurrentTimePropertyInfo
data DOMMediaControllerDefaultPlaybackRatePropertyInfo
data DOMMediaControllerDurationPropertyInfo
data DOMMediaControllerMutedPropertyInfo
data DOMMediaControllerPausedPropertyInfo
data DOMMediaControllerPlaybackRatePropertyInfo
data DOMMediaControllerPlaybackStatePropertyInfo
data DOMMediaControllerPlayedPropertyInfo
data DOMMediaControllerSeekablePropertyInfo
data DOMMediaControllerVolumePropertyInfo
data DOMMediaControllerGetBufferedMethodInfo
data DOMMediaControllerGetCurrentTimeMethodInfo
data DOMMediaControllerGetDefaultPlaybackRateMethodInfo
data DOMMediaControllerGetDurationMethodInfo
data DOMMediaControllerGetMutedMethodInfo
data DOMMediaControllerGetPausedMethodInfo
data DOMMediaControllerGetPlaybackRateMethodInfo
data DOMMediaControllerGetPlaybackStateMethodInfo
data DOMMediaControllerGetPlayedMethodInfo
data DOMMediaControllerGetSeekableMethodInfo
data DOMMediaControllerGetVolumeMethodInfo
data DOMMediaControllerPauseMethodInfo
data DOMMediaControllerPlayMethodInfo
data DOMMediaControllerSetCurrentTimeMethodInfo
data DOMMediaControllerSetDefaultPlaybackRateMethodInfo
data DOMMediaControllerSetMutedMethodInfo
data DOMMediaControllerSetPlaybackRateMethodInfo
data DOMMediaControllerSetVolumeMethodInfo
data DOMMediaControllerUnpauseMethodInfo
