module GI.WebKit.Objects.DOMNavigator where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMNavigator = DOMNavigator (ForeignPtr DOMNavigator)
instance GObject DOMNavigator where
class GObject o => DOMNavigatorK o
instance (GObject o, IsDescendantOf DOMNavigator o) => DOMNavigatorK o
data DOMNavigatorAppCodeNamePropertyInfo
data DOMNavigatorAppNamePropertyInfo
data DOMNavigatorAppVersionPropertyInfo
data DOMNavigatorCookieEnabledPropertyInfo
data DOMNavigatorGeolocationPropertyInfo
data DOMNavigatorLanguagePropertyInfo
data DOMNavigatorMimeTypesPropertyInfo
data DOMNavigatorOnLinePropertyInfo
data DOMNavigatorPlatformPropertyInfo
data DOMNavigatorPluginsPropertyInfo
data DOMNavigatorProductPropertyInfo
data DOMNavigatorProductSubPropertyInfo
data DOMNavigatorUserAgentPropertyInfo
data DOMNavigatorVendorPropertyInfo
data DOMNavigatorVendorSubPropertyInfo
data DOMNavigatorWebkitBatteryPropertyInfo
data DOMNavigatorWebkitPersistentStoragePropertyInfo
data DOMNavigatorWebkitTemporaryStoragePropertyInfo
data DOMNavigatorGetAppCodeNameMethodInfo
data DOMNavigatorGetAppNameMethodInfo
data DOMNavigatorGetAppVersionMethodInfo
data DOMNavigatorGetCookieEnabledMethodInfo
data DOMNavigatorGetGeolocationMethodInfo
data DOMNavigatorGetLanguageMethodInfo
data DOMNavigatorGetMimeTypesMethodInfo
data DOMNavigatorGetOnLineMethodInfo
data DOMNavigatorGetPlatformMethodInfo
data DOMNavigatorGetPluginsMethodInfo
data DOMNavigatorGetProductMethodInfo
data DOMNavigatorGetProductSubMethodInfo
data DOMNavigatorGetStorageUpdatesMethodInfo
data DOMNavigatorGetUserAgentMethodInfo
data DOMNavigatorGetVendorMethodInfo
data DOMNavigatorGetVendorSubMethodInfo
data DOMNavigatorGetWebkitBatteryMethodInfo
data DOMNavigatorGetWebkitPersistentStorageMethodInfo
data DOMNavigatorGetWebkitTemporaryStorageMethodInfo
data DOMNavigatorIsProtocolHandlerRegisteredMethodInfo
data DOMNavigatorJavaEnabledMethodInfo
data DOMNavigatorRegisterProtocolHandlerMethodInfo
data DOMNavigatorUnregisterProtocolHandlerMethodInfo
data DOMNavigatorWebkitGetGamepadsMethodInfo
