module GI.WebKit.Objects.DOMPerformanceTiming where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DOMPerformanceTiming = DOMPerformanceTiming (ForeignPtr DOMPerformanceTiming)
instance GObject DOMPerformanceTiming where
class GObject o => DOMPerformanceTimingK o
instance (GObject o, IsDescendantOf DOMPerformanceTiming o) => DOMPerformanceTimingK o
data DOMPerformanceTimingConnectEndPropertyInfo
data DOMPerformanceTimingConnectStartPropertyInfo
data DOMPerformanceTimingDomCompletePropertyInfo
data DOMPerformanceTimingDomContentLoadedEventEndPropertyInfo
data DOMPerformanceTimingDomContentLoadedEventStartPropertyInfo
data DOMPerformanceTimingDomInteractivePropertyInfo
data DOMPerformanceTimingDomLoadingPropertyInfo
data DOMPerformanceTimingDomainLookupEndPropertyInfo
data DOMPerformanceTimingDomainLookupStartPropertyInfo
data DOMPerformanceTimingFetchStartPropertyInfo
data DOMPerformanceTimingLoadEventEndPropertyInfo
data DOMPerformanceTimingLoadEventStartPropertyInfo
data DOMPerformanceTimingNavigationStartPropertyInfo
data DOMPerformanceTimingRedirectEndPropertyInfo
data DOMPerformanceTimingRedirectStartPropertyInfo
data DOMPerformanceTimingRequestStartPropertyInfo
data DOMPerformanceTimingResponseEndPropertyInfo
data DOMPerformanceTimingResponseStartPropertyInfo
data DOMPerformanceTimingSecureConnectionStartPropertyInfo
data DOMPerformanceTimingUnloadEventEndPropertyInfo
data DOMPerformanceTimingUnloadEventStartPropertyInfo
data DOMPerformanceTimingGetConnectEndMethodInfo
data DOMPerformanceTimingGetConnectStartMethodInfo
data DOMPerformanceTimingGetDomCompleteMethodInfo
data DOMPerformanceTimingGetDomContentLoadedEventEndMethodInfo
data DOMPerformanceTimingGetDomContentLoadedEventStartMethodInfo
data DOMPerformanceTimingGetDomInteractiveMethodInfo
data DOMPerformanceTimingGetDomLoadingMethodInfo
data DOMPerformanceTimingGetDomainLookupEndMethodInfo
data DOMPerformanceTimingGetDomainLookupStartMethodInfo
data DOMPerformanceTimingGetFetchStartMethodInfo
data DOMPerformanceTimingGetLoadEventEndMethodInfo
data DOMPerformanceTimingGetLoadEventStartMethodInfo
data DOMPerformanceTimingGetNavigationStartMethodInfo
data DOMPerformanceTimingGetRedirectEndMethodInfo
data DOMPerformanceTimingGetRedirectStartMethodInfo
data DOMPerformanceTimingGetRequestStartMethodInfo
data DOMPerformanceTimingGetResponseEndMethodInfo
data DOMPerformanceTimingGetResponseStartMethodInfo
data DOMPerformanceTimingGetSecureConnectionStartMethodInfo
data DOMPerformanceTimingGetUnloadEventEndMethodInfo
data DOMPerformanceTimingGetUnloadEventStartMethodInfo
