module GI.Gio.Structs.DBusInterfaceInfo where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DBusInterfaceInfo = DBusInterfaceInfo (ForeignPtr DBusInterfaceInfo)
instance BoxedObject DBusInterfaceInfo where
data DBusInterfaceInfoCacheBuildMethodInfo
data DBusInterfaceInfoCacheReleaseMethodInfo
data DBusInterfaceInfoGenerateXmlMethodInfo
data DBusInterfaceInfoLookupMethodMethodInfo
data DBusInterfaceInfoLookupPropertyMethodInfo
data DBusInterfaceInfoLookupSignalMethodInfo
data DBusInterfaceInfoRefMethodInfo
data DBusInterfaceInfoUnrefMethodInfo
