module GI.GstBase.Structs.ByteReader where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype ByteReader = ByteReader (ForeignPtr ByteReader)
data ByteReaderDupDataMethodInfo
data ByteReaderDupStringUtf16MethodInfo
data ByteReaderDupStringUtf32MethodInfo
data ByteReaderDupStringUtf8MethodInfo
data ByteReaderFreeMethodInfo
data ByteReaderGetDataMethodInfo
data ByteReaderGetFloat32BeMethodInfo
data ByteReaderGetFloat32LeMethodInfo
data ByteReaderGetFloat64BeMethodInfo
data ByteReaderGetFloat64LeMethodInfo
data ByteReaderGetInt16BeMethodInfo
data ByteReaderGetInt16LeMethodInfo
data ByteReaderGetInt24BeMethodInfo
data ByteReaderGetInt24LeMethodInfo
data ByteReaderGetInt32BeMethodInfo
data ByteReaderGetInt32LeMethodInfo
data ByteReaderGetInt64BeMethodInfo
data ByteReaderGetInt64LeMethodInfo
data ByteReaderGetInt8MethodInfo
data ByteReaderGetPosMethodInfo
data ByteReaderGetRemainingMethodInfo
data ByteReaderGetSizeMethodInfo
data ByteReaderGetStringUtf8MethodInfo
data ByteReaderGetUint16BeMethodInfo
data ByteReaderGetUint16LeMethodInfo
data ByteReaderGetUint24BeMethodInfo
data ByteReaderGetUint24LeMethodInfo
data ByteReaderGetUint32BeMethodInfo
data ByteReaderGetUint32LeMethodInfo
data ByteReaderGetUint64BeMethodInfo
data ByteReaderGetUint64LeMethodInfo
data ByteReaderGetUint8MethodInfo
data ByteReaderInitMethodInfo
data ByteReaderMaskedScanUint32MethodInfo
data ByteReaderMaskedScanUint32PeekMethodInfo
data ByteReaderPeekDataMethodInfo
data ByteReaderPeekFloat32BeMethodInfo
data ByteReaderPeekFloat32LeMethodInfo
data ByteReaderPeekFloat64BeMethodInfo
data ByteReaderPeekFloat64LeMethodInfo
data ByteReaderPeekInt16BeMethodInfo
data ByteReaderPeekInt16LeMethodInfo
data ByteReaderPeekInt24BeMethodInfo
data ByteReaderPeekInt24LeMethodInfo
data ByteReaderPeekInt32BeMethodInfo
data ByteReaderPeekInt32LeMethodInfo
data ByteReaderPeekInt64BeMethodInfo
data ByteReaderPeekInt64LeMethodInfo
data ByteReaderPeekInt8MethodInfo
data ByteReaderPeekStringUtf8MethodInfo
data ByteReaderPeekUint16BeMethodInfo
data ByteReaderPeekUint16LeMethodInfo
data ByteReaderPeekUint24BeMethodInfo
data ByteReaderPeekUint24LeMethodInfo
data ByteReaderPeekUint32BeMethodInfo
data ByteReaderPeekUint32LeMethodInfo
data ByteReaderPeekUint64BeMethodInfo
data ByteReaderPeekUint64LeMethodInfo
data ByteReaderPeekUint8MethodInfo
data ByteReaderSetPosMethodInfo
data ByteReaderSkipMethodInfo
data ByteReaderSkipStringUtf16MethodInfo
data ByteReaderSkipStringUtf32MethodInfo
data ByteReaderSkipStringUtf8MethodInfo
