module GI.Poppler.Objects.StructureElement where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype StructureElement = StructureElement (ForeignPtr StructureElement)
instance GObject StructureElement where
class GObject o => StructureElementK o
instance (GObject o, IsDescendantOf StructureElement o) => StructureElementK o
data StructureElementGetAbbreviationMethodInfo
data StructureElementGetActualTextMethodInfo
data StructureElementGetAltTextMethodInfo
data StructureElementGetBackgroundColorMethodInfo
data StructureElementGetBaselineShiftMethodInfo
data StructureElementGetBlockAlignMethodInfo
data StructureElementGetBorderColorMethodInfo
data StructureElementGetBorderStyleMethodInfo
data StructureElementGetBorderThicknessMethodInfo
data StructureElementGetBoundingBoxMethodInfo
data StructureElementGetColorMethodInfo
data StructureElementGetColumnCountMethodInfo
data StructureElementGetColumnGapsMethodInfo
data StructureElementGetColumnWidthsMethodInfo
data StructureElementGetEndIndentMethodInfo
data StructureElementGetFormDescriptionMethodInfo
data StructureElementGetFormRoleMethodInfo
data StructureElementGetFormStateMethodInfo
data StructureElementGetGlyphOrientationMethodInfo
data StructureElementGetHeightMethodInfo
data StructureElementGetIdMethodInfo
data StructureElementGetInlineAlignMethodInfo
data StructureElementGetKindMethodInfo
data StructureElementGetLanguageMethodInfo
data StructureElementGetLineHeightMethodInfo
data StructureElementGetListNumberingMethodInfo
data StructureElementGetPaddingMethodInfo
data StructureElementGetPageMethodInfo
data StructureElementGetPlacementMethodInfo
data StructureElementGetRubyAlignMethodInfo
data StructureElementGetRubyPositionMethodInfo
data StructureElementGetSpaceAfterMethodInfo
data StructureElementGetSpaceBeforeMethodInfo
data StructureElementGetStartIndentMethodInfo
data StructureElementGetTableBorderStyleMethodInfo
data StructureElementGetTableColumnSpanMethodInfo
data StructureElementGetTableHeadersMethodInfo
data StructureElementGetTablePaddingMethodInfo
data StructureElementGetTableRowSpanMethodInfo
data StructureElementGetTableScopeMethodInfo
data StructureElementGetTableSummaryMethodInfo
data StructureElementGetTextMethodInfo
data StructureElementGetTextAlignMethodInfo
data StructureElementGetTextDecorationColorMethodInfo
data StructureElementGetTextDecorationThicknessMethodInfo
data StructureElementGetTextDecorationTypeMethodInfo
data StructureElementGetTextIndentMethodInfo
data StructureElementGetTextSpansMethodInfo
data StructureElementGetTitleMethodInfo
data StructureElementGetWidthMethodInfo
data StructureElementGetWritingModeMethodInfo
data StructureElementIsBlockMethodInfo
data StructureElementIsContentMethodInfo
data StructureElementIsGroupingMethodInfo
data StructureElementIsInlineMethodInfo
