module GI.GLib.Structs.MarkupParseContext where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype MarkupParseContext = MarkupParseContext (ForeignPtr MarkupParseContext)
instance BoxedObject MarkupParseContext where
data MarkupParseContextEndParseMethodInfo
data MarkupParseContextFreeMethodInfo
data MarkupParseContextGetElementMethodInfo
data MarkupParseContextGetUserDataMethodInfo
data MarkupParseContextParseMethodInfo
data MarkupParseContextPopMethodInfo
data MarkupParseContextPushMethodInfo
data MarkupParseContextRefMethodInfo
data MarkupParseContextUnrefMethodInfo
