module GI.Gtk.Structs.TextIter where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype TextIter = TextIter (ForeignPtr TextIter)
instance BoxedObject TextIter where
data TextIterAssignMethodInfo
data TextIterBackwardCharMethodInfo
data TextIterBackwardCharsMethodInfo
data TextIterBackwardCursorPositionMethodInfo
data TextIterBackwardCursorPositionsMethodInfo
data TextIterBackwardFindCharMethodInfo
data TextIterBackwardLineMethodInfo
data TextIterBackwardLinesMethodInfo
data TextIterBackwardSearchMethodInfo
data TextIterBackwardSentenceStartMethodInfo
data TextIterBackwardSentenceStartsMethodInfo
data TextIterBackwardToTagToggleMethodInfo
data TextIterBackwardVisibleCursorPositionMethodInfo
data TextIterBackwardVisibleCursorPositionsMethodInfo
data TextIterBackwardVisibleLineMethodInfo
data TextIterBackwardVisibleLinesMethodInfo
data TextIterBackwardVisibleWordStartMethodInfo
data TextIterBackwardVisibleWordStartsMethodInfo
data TextIterBackwardWordStartMethodInfo
data TextIterBackwardWordStartsMethodInfo
data TextIterBeginsTagMethodInfo
data TextIterCanInsertMethodInfo
data TextIterCompareMethodInfo
data TextIterCopyMethodInfo
data TextIterEditableMethodInfo
data TextIterEndsLineMethodInfo
data TextIterEndsSentenceMethodInfo
data TextIterEndsTagMethodInfo
data TextIterEndsWordMethodInfo
data TextIterEqualMethodInfo
data TextIterForwardCharMethodInfo
data TextIterForwardCharsMethodInfo
data TextIterForwardCursorPositionMethodInfo
data TextIterForwardCursorPositionsMethodInfo
data TextIterForwardFindCharMethodInfo
data TextIterForwardLineMethodInfo
data TextIterForwardLinesMethodInfo
data TextIterForwardSearchMethodInfo
data TextIterForwardSentenceEndMethodInfo
data TextIterForwardSentenceEndsMethodInfo
data TextIterForwardToEndMethodInfo
data TextIterForwardToLineEndMethodInfo
data TextIterForwardToTagToggleMethodInfo
data TextIterForwardVisibleCursorPositionMethodInfo
data TextIterForwardVisibleCursorPositionsMethodInfo
data TextIterForwardVisibleLineMethodInfo
data TextIterForwardVisibleLinesMethodInfo
data TextIterForwardVisibleWordEndMethodInfo
data TextIterForwardVisibleWordEndsMethodInfo
data TextIterForwardWordEndMethodInfo
data TextIterForwardWordEndsMethodInfo
data TextIterFreeMethodInfo
data TextIterGetAttributesMethodInfo
data TextIterGetBufferMethodInfo
data TextIterGetBytesInLineMethodInfo
data TextIterGetCharMethodInfo
data TextIterGetCharsInLineMethodInfo
data TextIterGetChildAnchorMethodInfo
data TextIterGetLanguageMethodInfo
data TextIterGetLineMethodInfo
data TextIterGetLineIndexMethodInfo
data TextIterGetLineOffsetMethodInfo
data TextIterGetMarksMethodInfo
data TextIterGetOffsetMethodInfo
data TextIterGetPixbufMethodInfo
data TextIterGetSliceMethodInfo
data TextIterGetTagsMethodInfo
data TextIterGetTextMethodInfo
data TextIterGetToggledTagsMethodInfo
data TextIterGetVisibleLineIndexMethodInfo
data TextIterGetVisibleLineOffsetMethodInfo
data TextIterGetVisibleSliceMethodInfo
data TextIterGetVisibleTextMethodInfo
data TextIterHasTagMethodInfo
data TextIterInRangeMethodInfo
data TextIterInsideSentenceMethodInfo
data TextIterInsideWordMethodInfo
data TextIterIsCursorPositionMethodInfo
data TextIterIsEndMethodInfo
data TextIterIsStartMethodInfo
data TextIterOrderMethodInfo
data TextIterSetLineMethodInfo
data TextIterSetLineIndexMethodInfo
data TextIterSetLineOffsetMethodInfo
data TextIterSetOffsetMethodInfo
data TextIterSetVisibleLineIndexMethodInfo
data TextIterSetVisibleLineOffsetMethodInfo
data TextIterStartsLineMethodInfo
data TextIterStartsSentenceMethodInfo
data TextIterStartsTagMethodInfo
data TextIterStartsWordMethodInfo
data TextIterTogglesTagMethodInfo
