module GI.Gio.Interfaces.DtlsClientConnection where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype DtlsClientConnection = DtlsClientConnection (ForeignPtr DtlsClientConnection)
data DtlsClientConnectionAcceptedCasPropertyInfo
data DtlsClientConnectionServerIdentityPropertyInfo
data DtlsClientConnectionValidationFlagsPropertyInfo
instance GObject DtlsClientConnection where
class GObject o => DtlsClientConnectionK o
instance (GObject o, IsDescendantOf DtlsClientConnection o) => DtlsClientConnectionK o
data DtlsClientConnectionGetAcceptedCasMethodInfo
data DtlsClientConnectionGetServerIdentityMethodInfo
data DtlsClientConnectionGetValidationFlagsMethodInfo
data DtlsClientConnectionSetServerIdentityMethodInfo
data DtlsClientConnectionSetValidationFlagsMethodInfo
