module GI.Pango.Structs.FontMetrics where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype FontMetrics = FontMetrics (ForeignPtr FontMetrics)
instance BoxedObject FontMetrics where
data FontMetricsGetApproximateCharWidthMethodInfo
data FontMetricsGetApproximateDigitWidthMethodInfo
data FontMetricsGetAscentMethodInfo
data FontMetricsGetDescentMethodInfo
data FontMetricsGetStrikethroughPositionMethodInfo
data FontMetricsGetStrikethroughThicknessMethodInfo
data FontMetricsGetUnderlinePositionMethodInfo
data FontMetricsGetUnderlineThicknessMethodInfo
data FontMetricsRefMethodInfo
data FontMetricsUnrefMethodInfo
