module GI.Gtk.Objects.CellRendererText where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype CellRendererText = CellRendererText (ForeignPtr CellRendererText)
instance GObject CellRendererText where
class GObject o => CellRendererTextK o
instance (GObject o, IsDescendantOf CellRendererText o) => CellRendererTextK o
data CellRendererTextAlignSetPropertyInfo
data CellRendererTextAlignmentPropertyInfo
data CellRendererTextAttributesPropertyInfo
data CellRendererTextBackgroundPropertyInfo
data CellRendererTextBackgroundGdkPropertyInfo
data CellRendererTextBackgroundRgbaPropertyInfo
data CellRendererTextBackgroundSetPropertyInfo
data CellRendererTextEditablePropertyInfo
data CellRendererTextEditableSetPropertyInfo
data CellRendererTextEllipsizePropertyInfo
data CellRendererTextEllipsizeSetPropertyInfo
data CellRendererTextFamilyPropertyInfo
data CellRendererTextFamilySetPropertyInfo
data CellRendererTextFontPropertyInfo
data CellRendererTextFontDescPropertyInfo
data CellRendererTextForegroundPropertyInfo
data CellRendererTextForegroundGdkPropertyInfo
data CellRendererTextForegroundRgbaPropertyInfo
data CellRendererTextForegroundSetPropertyInfo
data CellRendererTextLanguagePropertyInfo
data CellRendererTextLanguageSetPropertyInfo
data CellRendererTextMarkupPropertyInfo
data CellRendererTextMaxWidthCharsPropertyInfo
data CellRendererTextPlaceholderTextPropertyInfo
data CellRendererTextRisePropertyInfo
data CellRendererTextRiseSetPropertyInfo
data CellRendererTextScalePropertyInfo
data CellRendererTextScaleSetPropertyInfo
data CellRendererTextSingleParagraphModePropertyInfo
data CellRendererTextSizePropertyInfo
data CellRendererTextSizePointsPropertyInfo
data CellRendererTextSizeSetPropertyInfo
data CellRendererTextStretchPropertyInfo
data CellRendererTextStretchSetPropertyInfo
data CellRendererTextStrikethroughPropertyInfo
data CellRendererTextStrikethroughSetPropertyInfo
data CellRendererTextStylePropertyInfo
data CellRendererTextStyleSetPropertyInfo
data CellRendererTextTextPropertyInfo
data CellRendererTextUnderlinePropertyInfo
data CellRendererTextUnderlineSetPropertyInfo
data CellRendererTextVariantPropertyInfo
data CellRendererTextVariantSetPropertyInfo
data CellRendererTextWeightPropertyInfo
data CellRendererTextWeightSetPropertyInfo
data CellRendererTextWidthCharsPropertyInfo
data CellRendererTextWrapModePropertyInfo
data CellRendererTextWrapWidthPropertyInfo
data CellRendererTextEditedSignalInfo
data CellRendererTextSetFixedHeightFromFontMethodInfo
