module GI.Gtk.Objects.EntryCompletion where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype EntryCompletion = EntryCompletion (ForeignPtr EntryCompletion)
instance GObject EntryCompletion where
class GObject o => EntryCompletionK o
instance (GObject o, IsDescendantOf EntryCompletion o) => EntryCompletionK o
data EntryCompletionCellAreaPropertyInfo
data EntryCompletionInlineCompletionPropertyInfo
data EntryCompletionInlineSelectionPropertyInfo
data EntryCompletionMinimumKeyLengthPropertyInfo
data EntryCompletionModelPropertyInfo
data EntryCompletionPopupCompletionPropertyInfo
data EntryCompletionPopupSetWidthPropertyInfo
data EntryCompletionPopupSingleMatchPropertyInfo
data EntryCompletionTextColumnPropertyInfo
data EntryCompletionActionActivatedSignalInfo
data EntryCompletionCursorOnMatchSignalInfo
data EntryCompletionInsertPrefixSignalInfo
data EntryCompletionMatchSelectedSignalInfo
data EntryCompletionNoMatchesSignalInfo
data EntryCompletionCompleteMethodInfo
data EntryCompletionComputePrefixMethodInfo
data EntryCompletionDeleteActionMethodInfo
data EntryCompletionGetCompletionPrefixMethodInfo
data EntryCompletionGetEntryMethodInfo
data EntryCompletionGetInlineCompletionMethodInfo
data EntryCompletionGetInlineSelectionMethodInfo
data EntryCompletionGetMinimumKeyLengthMethodInfo
data EntryCompletionGetModelMethodInfo
data EntryCompletionGetPopupCompletionMethodInfo
data EntryCompletionGetPopupSetWidthMethodInfo
data EntryCompletionGetPopupSingleMatchMethodInfo
data EntryCompletionGetTextColumnMethodInfo
data EntryCompletionInsertActionMarkupMethodInfo
data EntryCompletionInsertActionTextMethodInfo
data EntryCompletionInsertPrefixMethodInfo
data EntryCompletionSetInlineCompletionMethodInfo
data EntryCompletionSetInlineSelectionMethodInfo
data EntryCompletionSetMatchFuncMethodInfo
data EntryCompletionSetMinimumKeyLengthMethodInfo
data EntryCompletionSetModelMethodInfo
data EntryCompletionSetPopupCompletionMethodInfo
data EntryCompletionSetPopupSetWidthMethodInfo
data EntryCompletionSetPopupSingleMatchMethodInfo
data EntryCompletionSetTextColumnMethodInfo
