module GI.Gtk.Objects.PlacesSidebar where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype PlacesSidebar = PlacesSidebar (ForeignPtr PlacesSidebar)
instance GObject PlacesSidebar where
class GObject o => PlacesSidebarK o
instance (GObject o, IsDescendantOf PlacesSidebar o) => PlacesSidebarK o
data PlacesSidebarLocalOnlyPropertyInfo
data PlacesSidebarLocationPropertyInfo
data PlacesSidebarOpenFlagsPropertyInfo
data PlacesSidebarPopulateAllPropertyInfo
data PlacesSidebarShowConnectToServerPropertyInfo
data PlacesSidebarShowDesktopPropertyInfo
data PlacesSidebarShowEnterLocationPropertyInfo
data PlacesSidebarShowOtherLocationsPropertyInfo
data PlacesSidebarShowRecentPropertyInfo
data PlacesSidebarShowTrashPropertyInfo
data PlacesSidebarDragActionAskSignalInfo
data PlacesSidebarDragActionRequestedSignalInfo
data PlacesSidebarDragPerformDropSignalInfo
data PlacesSidebarMountSignalInfo
data PlacesSidebarOpenLocationSignalInfo
data PlacesSidebarPopulatePopupSignalInfo
data PlacesSidebarShowConnectToServerSignalInfo
data PlacesSidebarShowEnterLocationSignalInfo
data PlacesSidebarShowErrorMessageSignalInfo
data PlacesSidebarShowOtherLocationsSignalInfo
data PlacesSidebarShowOtherLocationsWithFlagsSignalInfo
data PlacesSidebarUnmountSignalInfo
data PlacesSidebarAddShortcutMethodInfo
data PlacesSidebarGetLocalOnlyMethodInfo
data PlacesSidebarGetLocationMethodInfo
data PlacesSidebarGetNthBookmarkMethodInfo
data PlacesSidebarGetOpenFlagsMethodInfo
data PlacesSidebarGetShowConnectToServerMethodInfo
data PlacesSidebarGetShowDesktopMethodInfo
data PlacesSidebarGetShowEnterLocationMethodInfo
data PlacesSidebarGetShowOtherLocationsMethodInfo
data PlacesSidebarGetShowRecentMethodInfo
data PlacesSidebarGetShowTrashMethodInfo
data PlacesSidebarListShortcutsMethodInfo
data PlacesSidebarRemoveShortcutMethodInfo
data PlacesSidebarSetDropTargetsVisibleMethodInfo
data PlacesSidebarSetLocalOnlyMethodInfo
data PlacesSidebarSetLocationMethodInfo
data PlacesSidebarSetOpenFlagsMethodInfo
data PlacesSidebarSetShowConnectToServerMethodInfo
data PlacesSidebarSetShowDesktopMethodInfo
data PlacesSidebarSetShowEnterLocationMethodInfo
data PlacesSidebarSetShowOtherLocationsMethodInfo
data PlacesSidebarSetShowRecentMethodInfo
data PlacesSidebarSetShowTrashMethodInfo
