module GI.Gtk.Objects.PrintOperation where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype PrintOperation = PrintOperation (ForeignPtr PrintOperation)
instance GObject PrintOperation where
class GObject o => PrintOperationK o
instance (GObject o, IsDescendantOf PrintOperation o) => PrintOperationK o
data PrintOperationAllowAsyncPropertyInfo
data PrintOperationCurrentPagePropertyInfo
data PrintOperationCustomTabLabelPropertyInfo
data PrintOperationDefaultPageSetupPropertyInfo
data PrintOperationEmbedPageSetupPropertyInfo
data PrintOperationExportFilenamePropertyInfo
data PrintOperationHasSelectionPropertyInfo
data PrintOperationJobNamePropertyInfo
data PrintOperationNPagesPropertyInfo
data PrintOperationNPagesToPrintPropertyInfo
data PrintOperationPrintSettingsPropertyInfo
data PrintOperationShowProgressPropertyInfo
data PrintOperationStatusPropertyInfo
data PrintOperationStatusStringPropertyInfo
data PrintOperationSupportSelectionPropertyInfo
data PrintOperationTrackPrintStatusPropertyInfo
data PrintOperationUnitPropertyInfo
data PrintOperationUseFullPagePropertyInfo
data PrintOperationBeginPrintSignalInfo
data PrintOperationCreateCustomWidgetSignalInfo
data PrintOperationCustomWidgetApplySignalInfo
data PrintOperationDoneSignalInfo
data PrintOperationDrawPageSignalInfo
data PrintOperationEndPrintSignalInfo
data PrintOperationPaginateSignalInfo
data PrintOperationPreviewSignalInfo
data PrintOperationRequestPageSetupSignalInfo
data PrintOperationStatusChangedSignalInfo
data PrintOperationUpdateCustomWidgetSignalInfo
data PrintOperationCancelMethodInfo
data PrintOperationDrawPageFinishMethodInfo
data PrintOperationGetDefaultPageSetupMethodInfo
data PrintOperationGetEmbedPageSetupMethodInfo
data PrintOperationGetErrorMethodInfo
data PrintOperationGetHasSelectionMethodInfo
data PrintOperationGetNPagesToPrintMethodInfo
data PrintOperationGetPrintSettingsMethodInfo
data PrintOperationGetStatusMethodInfo
data PrintOperationGetStatusStringMethodInfo
data PrintOperationGetSupportSelectionMethodInfo
data PrintOperationIsFinishedMethodInfo
data PrintOperationRunMethodInfo
data PrintOperationSetAllowAsyncMethodInfo
data PrintOperationSetCurrentPageMethodInfo
data PrintOperationSetCustomTabLabelMethodInfo
data PrintOperationSetDefaultPageSetupMethodInfo
data PrintOperationSetDeferDrawingMethodInfo
data PrintOperationSetEmbedPageSetupMethodInfo
data PrintOperationSetExportFilenameMethodInfo
data PrintOperationSetHasSelectionMethodInfo
data PrintOperationSetJobNameMethodInfo
data PrintOperationSetNPagesMethodInfo
data PrintOperationSetPrintSettingsMethodInfo
data PrintOperationSetShowProgressMethodInfo
data PrintOperationSetSupportSelectionMethodInfo
data PrintOperationSetTrackPrintStatusMethodInfo
data PrintOperationSetUnitMethodInfo
data PrintOperationSetUseFullPageMethodInfo
