module GI.Gtk.Objects.PrintSettings where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype PrintSettings = PrintSettings (ForeignPtr PrintSettings)
instance GObject PrintSettings where
class GObject o => PrintSettingsK o
instance (GObject o, IsDescendantOf PrintSettings o) => PrintSettingsK o
data PrintSettingsCopyMethodInfo
data PrintSettingsForeachMethodInfo
data PrintSettingsGetMethodInfo
data PrintSettingsGetBoolMethodInfo
data PrintSettingsGetCollateMethodInfo
data PrintSettingsGetDefaultSourceMethodInfo
data PrintSettingsGetDitherMethodInfo
data PrintSettingsGetDoubleMethodInfo
data PrintSettingsGetDoubleWithDefaultMethodInfo
data PrintSettingsGetDuplexMethodInfo
data PrintSettingsGetFinishingsMethodInfo
data PrintSettingsGetIntMethodInfo
data PrintSettingsGetIntWithDefaultMethodInfo
data PrintSettingsGetLengthMethodInfo
data PrintSettingsGetMediaTypeMethodInfo
data PrintSettingsGetNCopiesMethodInfo
data PrintSettingsGetNumberUpMethodInfo
data PrintSettingsGetNumberUpLayoutMethodInfo
data PrintSettingsGetOrientationMethodInfo
data PrintSettingsGetOutputBinMethodInfo
data PrintSettingsGetPageRangesMethodInfo
data PrintSettingsGetPageSetMethodInfo
data PrintSettingsGetPaperHeightMethodInfo
data PrintSettingsGetPaperSizeMethodInfo
data PrintSettingsGetPaperWidthMethodInfo
data PrintSettingsGetPrintPagesMethodInfo
data PrintSettingsGetPrinterMethodInfo
data PrintSettingsGetPrinterLpiMethodInfo
data PrintSettingsGetQualityMethodInfo
data PrintSettingsGetResolutionMethodInfo
data PrintSettingsGetResolutionXMethodInfo
data PrintSettingsGetResolutionYMethodInfo
data PrintSettingsGetReverseMethodInfo
data PrintSettingsGetScaleMethodInfo
data PrintSettingsGetUseColorMethodInfo
data PrintSettingsHasKeyMethodInfo
data PrintSettingsLoadFileMethodInfo
data PrintSettingsLoadKeyFileMethodInfo
data PrintSettingsSetMethodInfo
data PrintSettingsSetBoolMethodInfo
data PrintSettingsSetCollateMethodInfo
data PrintSettingsSetDefaultSourceMethodInfo
data PrintSettingsSetDitherMethodInfo
data PrintSettingsSetDoubleMethodInfo
data PrintSettingsSetDuplexMethodInfo
data PrintSettingsSetFinishingsMethodInfo
data PrintSettingsSetIntMethodInfo
data PrintSettingsSetLengthMethodInfo
data PrintSettingsSetMediaTypeMethodInfo
data PrintSettingsSetNCopiesMethodInfo
data PrintSettingsSetNumberUpMethodInfo
data PrintSettingsSetNumberUpLayoutMethodInfo
data PrintSettingsSetOrientationMethodInfo
data PrintSettingsSetOutputBinMethodInfo
data PrintSettingsSetPageRangesMethodInfo
data PrintSettingsSetPageSetMethodInfo
data PrintSettingsSetPaperHeightMethodInfo
data PrintSettingsSetPaperSizeMethodInfo
data PrintSettingsSetPaperWidthMethodInfo
data PrintSettingsSetPrintPagesMethodInfo
data PrintSettingsSetPrinterMethodInfo
data PrintSettingsSetPrinterLpiMethodInfo
data PrintSettingsSetQualityMethodInfo
data PrintSettingsSetResolutionMethodInfo
data PrintSettingsSetResolutionXyMethodInfo
data PrintSettingsSetReverseMethodInfo
data PrintSettingsSetScaleMethodInfo
data PrintSettingsSetUseColorMethodInfo
data PrintSettingsToFileMethodInfo
data PrintSettingsToKeyFileMethodInfo
data PrintSettingsUnsetMethodInfo
