module GI.Gtk.Objects.TextBuffer where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype TextBuffer = TextBuffer (ForeignPtr TextBuffer)
instance GObject TextBuffer where
class GObject o => TextBufferK o
instance (GObject o, IsDescendantOf TextBuffer o) => TextBufferK o
data TextBufferCopyTargetListPropertyInfo
data TextBufferCursorPositionPropertyInfo
data TextBufferHasSelectionPropertyInfo
data TextBufferPasteTargetListPropertyInfo
data TextBufferTagTablePropertyInfo
data TextBufferTextPropertyInfo
data TextBufferApplyTagSignalInfo
data TextBufferBeginUserActionSignalInfo
data TextBufferChangedSignalInfo
data TextBufferDeleteRangeSignalInfo
data TextBufferEndUserActionSignalInfo
data TextBufferInsertChildAnchorSignalInfo
data TextBufferInsertPixbufSignalInfo
data TextBufferInsertTextSignalInfo
data TextBufferMarkDeletedSignalInfo
data TextBufferMarkSetSignalInfo
data TextBufferModifiedChangedSignalInfo
data TextBufferPasteDoneSignalInfo
data TextBufferRemoveTagSignalInfo
data TextBufferAddMarkMethodInfo
data TextBufferAddSelectionClipboardMethodInfo
data TextBufferApplyTagMethodInfo
data TextBufferApplyTagByNameMethodInfo
data TextBufferBackspaceMethodInfo
data TextBufferBeginUserActionMethodInfo
data TextBufferCopyClipboardMethodInfo
data TextBufferCreateChildAnchorMethodInfo
data TextBufferCreateMarkMethodInfo
data TextBufferCutClipboardMethodInfo
data TextBufferDeleteMethodInfo
data TextBufferDeleteInteractiveMethodInfo
data TextBufferDeleteMarkMethodInfo
data TextBufferDeleteMarkByNameMethodInfo
data TextBufferDeleteSelectionMethodInfo
data TextBufferDeserializeMethodInfo
data TextBufferDeserializeGetCanCreateTagsMethodInfo
data TextBufferDeserializeSetCanCreateTagsMethodInfo
data TextBufferEndUserActionMethodInfo
data TextBufferGetBoundsMethodInfo
data TextBufferGetCharCountMethodInfo
data TextBufferGetCopyTargetListMethodInfo
data TextBufferGetDeserializeFormatsMethodInfo
data TextBufferGetEndIterMethodInfo
data TextBufferGetHasSelectionMethodInfo
data TextBufferGetInsertMethodInfo
data TextBufferGetIterAtChildAnchorMethodInfo
data TextBufferGetIterAtLineMethodInfo
data TextBufferGetIterAtLineIndexMethodInfo
data TextBufferGetIterAtLineOffsetMethodInfo
data TextBufferGetIterAtMarkMethodInfo
data TextBufferGetIterAtOffsetMethodInfo
data TextBufferGetLineCountMethodInfo
data TextBufferGetMarkMethodInfo
data TextBufferGetModifiedMethodInfo
data TextBufferGetPasteTargetListMethodInfo
data TextBufferGetSelectionBoundMethodInfo
data TextBufferGetSelectionBoundsMethodInfo
data TextBufferGetSerializeFormatsMethodInfo
data TextBufferGetSliceMethodInfo
data TextBufferGetStartIterMethodInfo
data TextBufferGetTagTableMethodInfo
data TextBufferGetTextMethodInfo
data TextBufferInsertMethodInfo
data TextBufferInsertAtCursorMethodInfo
data TextBufferInsertChildAnchorMethodInfo
data TextBufferInsertInteractiveMethodInfo
data TextBufferInsertInteractiveAtCursorMethodInfo
data TextBufferInsertMarkupMethodInfo
data TextBufferInsertPixbufMethodInfo
data TextBufferInsertRangeMethodInfo
data TextBufferInsertRangeInteractiveMethodInfo
data TextBufferMoveMarkMethodInfo
data TextBufferMoveMarkByNameMethodInfo
data TextBufferPasteClipboardMethodInfo
data TextBufferPlaceCursorMethodInfo
data TextBufferRegisterDeserializeFormatMethodInfo
data TextBufferRegisterDeserializeTagsetMethodInfo
data TextBufferRegisterSerializeFormatMethodInfo
data TextBufferRegisterSerializeTagsetMethodInfo
data TextBufferRemoveAllTagsMethodInfo
data TextBufferRemoveSelectionClipboardMethodInfo
data TextBufferRemoveTagMethodInfo
data TextBufferRemoveTagByNameMethodInfo
data TextBufferSelectRangeMethodInfo
data TextBufferSerializeMethodInfo
data TextBufferSetModifiedMethodInfo
data TextBufferSetTextMethodInfo
data TextBufferUnregisterDeserializeFormatMethodInfo
data TextBufferUnregisterSerializeFormatMethodInfo
