module GI.Gtk.Objects.ToolItemGroup where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype ToolItemGroup = ToolItemGroup (ForeignPtr ToolItemGroup)
instance GObject ToolItemGroup where
class GObject o => ToolItemGroupK o
instance (GObject o, IsDescendantOf ToolItemGroup o) => ToolItemGroupK o
data ToolItemGroupCollapsedPropertyInfo
data ToolItemGroupEllipsizePropertyInfo
data ToolItemGroupHeaderReliefPropertyInfo
data ToolItemGroupLabelPropertyInfo
data ToolItemGroupLabelWidgetPropertyInfo
data ToolItemGroupGetCollapsedMethodInfo
data ToolItemGroupGetDropItemMethodInfo
data ToolItemGroupGetEllipsizeMethodInfo
data ToolItemGroupGetHeaderReliefMethodInfo
data ToolItemGroupGetItemPositionMethodInfo
data ToolItemGroupGetLabelMethodInfo
data ToolItemGroupGetLabelWidgetMethodInfo
data ToolItemGroupGetNItemsMethodInfo
data ToolItemGroupGetNthItemMethodInfo
data ToolItemGroupInsertMethodInfo
data ToolItemGroupSetCollapsedMethodInfo
data ToolItemGroupSetEllipsizeMethodInfo
data ToolItemGroupSetHeaderReliefMethodInfo
data ToolItemGroupSetItemPositionMethodInfo
data ToolItemGroupSetLabelMethodInfo
data ToolItemGroupSetLabelWidgetMethodInfo
