module GI.Gtk.Objects.TreeViewColumn where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype TreeViewColumn = TreeViewColumn (ForeignPtr TreeViewColumn)
instance GObject TreeViewColumn where
class GObject o => TreeViewColumnK o
instance (GObject o, IsDescendantOf TreeViewColumn o) => TreeViewColumnK o
data TreeViewColumnAlignmentPropertyInfo
data TreeViewColumnCellAreaPropertyInfo
data TreeViewColumnClickablePropertyInfo
data TreeViewColumnExpandPropertyInfo
data TreeViewColumnFixedWidthPropertyInfo
data TreeViewColumnMaxWidthPropertyInfo
data TreeViewColumnMinWidthPropertyInfo
data TreeViewColumnReorderablePropertyInfo
data TreeViewColumnResizablePropertyInfo
data TreeViewColumnSizingPropertyInfo
data TreeViewColumnSortColumnIdPropertyInfo
data TreeViewColumnSortIndicatorPropertyInfo
data TreeViewColumnSortOrderPropertyInfo
data TreeViewColumnSpacingPropertyInfo
data TreeViewColumnTitlePropertyInfo
data TreeViewColumnVisiblePropertyInfo
data TreeViewColumnWidgetPropertyInfo
data TreeViewColumnWidthPropertyInfo
data TreeViewColumnXOffsetPropertyInfo
data TreeViewColumnClickedSignalInfo
data TreeViewColumnAddAttributeMethodInfo
data TreeViewColumnCellGetPositionMethodInfo
data TreeViewColumnCellGetSizeMethodInfo
data TreeViewColumnCellIsVisibleMethodInfo
data TreeViewColumnCellSetCellDataMethodInfo
data TreeViewColumnClearMethodInfo
data TreeViewColumnClearAttributesMethodInfo
data TreeViewColumnClickedMethodInfo
data TreeViewColumnFocusCellMethodInfo
data TreeViewColumnGetAlignmentMethodInfo
data TreeViewColumnGetButtonMethodInfo
data TreeViewColumnGetClickableMethodInfo
data TreeViewColumnGetExpandMethodInfo
data TreeViewColumnGetFixedWidthMethodInfo
data TreeViewColumnGetMaxWidthMethodInfo
data TreeViewColumnGetMinWidthMethodInfo
data TreeViewColumnGetReorderableMethodInfo
data TreeViewColumnGetResizableMethodInfo
data TreeViewColumnGetSizingMethodInfo
data TreeViewColumnGetSortColumnIdMethodInfo
data TreeViewColumnGetSortIndicatorMethodInfo
data TreeViewColumnGetSortOrderMethodInfo
data TreeViewColumnGetSpacingMethodInfo
data TreeViewColumnGetTitleMethodInfo
data TreeViewColumnGetTreeViewMethodInfo
data TreeViewColumnGetVisibleMethodInfo
data TreeViewColumnGetWidgetMethodInfo
data TreeViewColumnGetWidthMethodInfo
data TreeViewColumnGetXOffsetMethodInfo
data TreeViewColumnPackEndMethodInfo
data TreeViewColumnPackStartMethodInfo
data TreeViewColumnQueueResizeMethodInfo
data TreeViewColumnSetAlignmentMethodInfo
data TreeViewColumnSetCellDataFuncMethodInfo
data TreeViewColumnSetClickableMethodInfo
data TreeViewColumnSetExpandMethodInfo
data TreeViewColumnSetFixedWidthMethodInfo
data TreeViewColumnSetMaxWidthMethodInfo
data TreeViewColumnSetMinWidthMethodInfo
data TreeViewColumnSetReorderableMethodInfo
data TreeViewColumnSetResizableMethodInfo
data TreeViewColumnSetSizingMethodInfo
data TreeViewColumnSetSortColumnIdMethodInfo
data TreeViewColumnSetSortIndicatorMethodInfo
data TreeViewColumnSetSortOrderMethodInfo
data TreeViewColumnSetSpacingMethodInfo
data TreeViewColumnSetTitleMethodInfo
data TreeViewColumnSetVisibleMethodInfo
data TreeViewColumnSetWidgetMethodInfo
