module GI.GtkSource.Objects.PrintCompositor where

import Data.GI.Base.ShortPrelude

import qualified Data.GI.Base.Attributes as GI.Attributes
import qualified Data.Text as T
import qualified Data.ByteString.Char8 as B
import qualified Data.Map as Map

newtype PrintCompositor = PrintCompositor (ForeignPtr PrintCompositor)
instance GObject PrintCompositor where
class GObject o => PrintCompositorK o
instance (GObject o, IsDescendantOf PrintCompositor o) => PrintCompositorK o
data PrintCompositorBodyFontNamePropertyInfo
data PrintCompositorBufferPropertyInfo
data PrintCompositorFooterFontNamePropertyInfo
data PrintCompositorHeaderFontNamePropertyInfo
data PrintCompositorHighlightSyntaxPropertyInfo
data PrintCompositorLineNumbersFontNamePropertyInfo
data PrintCompositorNPagesPropertyInfo
data PrintCompositorPrintFooterPropertyInfo
data PrintCompositorPrintHeaderPropertyInfo
data PrintCompositorPrintLineNumbersPropertyInfo
data PrintCompositorTabWidthPropertyInfo
data PrintCompositorWrapModePropertyInfo
data PrintCompositorDrawPageMethodInfo
data PrintCompositorGetBodyFontNameMethodInfo
data PrintCompositorGetBottomMarginMethodInfo
data PrintCompositorGetBufferMethodInfo
data PrintCompositorGetFooterFontNameMethodInfo
data PrintCompositorGetHeaderFontNameMethodInfo
data PrintCompositorGetHighlightSyntaxMethodInfo
data PrintCompositorGetLeftMarginMethodInfo
data PrintCompositorGetLineNumbersFontNameMethodInfo
data PrintCompositorGetNPagesMethodInfo
data PrintCompositorGetPaginationProgressMethodInfo
data PrintCompositorGetPrintFooterMethodInfo
data PrintCompositorGetPrintHeaderMethodInfo
data PrintCompositorGetPrintLineNumbersMethodInfo
data PrintCompositorGetRightMarginMethodInfo
data PrintCompositorGetTabWidthMethodInfo
data PrintCompositorGetTopMarginMethodInfo
data PrintCompositorGetWrapModeMethodInfo
data PrintCompositorPaginateMethodInfo
data PrintCompositorSetBodyFontNameMethodInfo
data PrintCompositorSetBottomMarginMethodInfo
data PrintCompositorSetFooterFontNameMethodInfo
data PrintCompositorSetFooterFormatMethodInfo
data PrintCompositorSetHeaderFontNameMethodInfo
data PrintCompositorSetHeaderFormatMethodInfo
data PrintCompositorSetHighlightSyntaxMethodInfo
data PrintCompositorSetLeftMarginMethodInfo
data PrintCompositorSetLineNumbersFontNameMethodInfo
data PrintCompositorSetPrintFooterMethodInfo
data PrintCompositorSetPrintHeaderMethodInfo
data PrintCompositorSetPrintLineNumbersMethodInfo
data PrintCompositorSetRightMarginMethodInfo
data PrintCompositorSetTabWidthMethodInfo
data PrintCompositorSetTopMarginMethodInfo
data PrintCompositorSetWrapModeMethodInfo
